/**
 * This file was generator by Fwmf Generated
 * ！！！Do not modify this file！！ 
 *
 * @fwmf.generated 2018-12-12 08:48:52
 */
package cn.faury.fwmf.module.api.category.generate.bean;

/**
 * Database Table Remarks:
 *   分类信息表
 *
 * This class was generated by Fwmf Generated.
 * This class corresponds to the database table product_t_category_info
 *
 * @fwmf.generated 2018-12-12 08:48:52
 */
public class CategoryInfoGenerateBean {
    /**
     * Database Column Remarks:
     *   分类ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column product_t_category_info.PRODUCT_CATEGORY_ID
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    private Long productCategoryId;

    /**
     * Database Column Remarks:
     *   分类名称
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column product_t_category_info.PRODUCT_CATEGORY_NAME
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    private String productCategoryName;

    /**
     * Database Column Remarks:
     *   显示顺序
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column product_t_category_info.DISPLAY_ORDER
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    private Integer displayOrder;

    /**
     * Database Column Remarks:
     *   父节点ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column product_t_category_info.PARENT_ID
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    private Long parentId;

    /**
     * Database Column Remarks:
     *   图标(可以是url也可以是相对路径，项目自定义)
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column product_t_category_info.ICON_PATH
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    private String iconPath;

    /**
     * Database Column Remarks:
     *   用途编码（1、2、4、8、16、32）
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column product_t_category_info.USAGE_CODE
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    private Integer usageCode;

    /**
     * Database Column Remarks:
     *   是否删除（Y：是  N：否）
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column product_t_category_info.IS_DELETE
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    private String isDelete;

    /**
     * Database Column Remarks:
     *   全路径
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column product_t_category_info.XPATH
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    private String xpath;

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column product_t_category_info.PRODUCT_CATEGORY_ID
     *
     * @return the value of product_t_category_info.PRODUCT_CATEGORY_ID
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    public Long getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column product_t_category_info.PRODUCT_CATEGORY_ID
     *
     * @param productCategoryId the value for product_t_category_info.PRODUCT_CATEGORY_ID
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    public void setProductCategoryId(Long productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column product_t_category_info.PRODUCT_CATEGORY_NAME
     *
     * @return the value of product_t_category_info.PRODUCT_CATEGORY_NAME
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    public String getProductCategoryName() {
        return productCategoryName;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column product_t_category_info.PRODUCT_CATEGORY_NAME
     *
     * @param productCategoryName the value for product_t_category_info.PRODUCT_CATEGORY_NAME
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    public void setProductCategoryName(String productCategoryName) {
        this.productCategoryName = productCategoryName == null ? null : productCategoryName.trim();
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column product_t_category_info.DISPLAY_ORDER
     *
     * @return the value of product_t_category_info.DISPLAY_ORDER
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column product_t_category_info.DISPLAY_ORDER
     *
     * @param displayOrder the value for product_t_category_info.DISPLAY_ORDER
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column product_t_category_info.PARENT_ID
     *
     * @return the value of product_t_category_info.PARENT_ID
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column product_t_category_info.PARENT_ID
     *
     * @param parentId the value for product_t_category_info.PARENT_ID
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column product_t_category_info.ICON_PATH
     *
     * @return the value of product_t_category_info.ICON_PATH
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    public String getIconPath() {
        return iconPath;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column product_t_category_info.ICON_PATH
     *
     * @param iconPath the value for product_t_category_info.ICON_PATH
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    public void setIconPath(String iconPath) {
        this.iconPath = iconPath == null ? null : iconPath.trim();
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column product_t_category_info.USAGE_CODE
     *
     * @return the value of product_t_category_info.USAGE_CODE
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    public Integer getUsageCode() {
        return usageCode;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column product_t_category_info.USAGE_CODE
     *
     * @param usageCode the value for product_t_category_info.USAGE_CODE
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    public void setUsageCode(Integer usageCode) {
        this.usageCode = usageCode;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column product_t_category_info.IS_DELETE
     *
     * @return the value of product_t_category_info.IS_DELETE
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column product_t_category_info.IS_DELETE
     *
     * @param isDelete the value for product_t_category_info.IS_DELETE
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column product_t_category_info.XPATH
     *
     * @return the value of product_t_category_info.XPATH
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    public String getXpath() {
        return xpath;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column product_t_category_info.XPATH
     *
     * @param xpath the value for product_t_category_info.XPATH
     *
     * @fwmf.generated 2018-12-12 08:48:52
     */
    public void setXpath(String xpath) {
        this.xpath = xpath == null ? null : xpath.trim();
    }
}