/**
 * This file was generator by Fwmf Generated
 * ！！！Do not modify this file！！ 
 *
 * @fwmf.generated 2018-11-14 17:14:30
 */
package cn.faury.fwmf.module.api.category.generate.bean;

/**
 * Database Table Remarks:
 *   分类授权业务系统
 *
 * This class was generated by Fwmf Generated.
 * This class corresponds to the database table product_t_category_r_system
 *
 * @fwmf.generated 2018-11-14 17:14:30
 */
public class SystemRCategoryGenerateBean {
    /**
     * Database Column Remarks:
     *   唯一标志
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column product_t_category_r_system.ID
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   业务系统ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column product_t_category_r_system.SYSTEM_ID
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    private Long systemId;

    /**
     * Database Column Remarks:
     *   分类ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column product_t_category_r_system.PRODUCT_CATEGORY_ID
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    private Long productCategoryId;

    /**
     * Database Column Remarks:
     *   模板ID（1、2、4、8、16、32）
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column product_t_category_r_system.TEMPLATE_ID
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    private Long templateId;

    /**
     * Database Column Remarks:
     *   是否为叶子节点【Y：是 N：否】
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column product_t_category_r_system.IS_LEAF
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    private String isLeaf;

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column product_t_category_r_system.ID
     *
     * @return the value of product_t_category_r_system.ID
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column product_t_category_r_system.ID
     *
     * @param id the value for product_t_category_r_system.ID
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column product_t_category_r_system.SYSTEM_ID
     *
     * @return the value of product_t_category_r_system.SYSTEM_ID
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    public Long getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column product_t_category_r_system.SYSTEM_ID
     *
     * @param systemId the value for product_t_category_r_system.SYSTEM_ID
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column product_t_category_r_system.PRODUCT_CATEGORY_ID
     *
     * @return the value of product_t_category_r_system.PRODUCT_CATEGORY_ID
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    public Long getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column product_t_category_r_system.PRODUCT_CATEGORY_ID
     *
     * @param productCategoryId the value for product_t_category_r_system.PRODUCT_CATEGORY_ID
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    public void setProductCategoryId(Long productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column product_t_category_r_system.TEMPLATE_ID
     *
     * @return the value of product_t_category_r_system.TEMPLATE_ID
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    public Long getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column product_t_category_r_system.TEMPLATE_ID
     *
     * @param templateId the value for product_t_category_r_system.TEMPLATE_ID
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column product_t_category_r_system.IS_LEAF
     *
     * @return the value of product_t_category_r_system.IS_LEAF
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    public String getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column product_t_category_r_system.IS_LEAF
     *
     * @param isLeaf the value for product_t_category_r_system.IS_LEAF
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    public void setIsLeaf(String isLeaf) {
        this.isLeaf = isLeaf == null ? null : isLeaf.trim();
    }
}