/**
 * This file was generator by Fwmf Generated
 * ！！！Do not modify this file！！ 
 *
 * @fwmf.generated 2018-09-26 11:34:22
 */
package cn.faury.fwmf.module.service.menu.generate.mapper;

import cn.faury.fwmf.module.api.menu.bean.MenuInfoBean;
import cn.faury.fwmf.module.api.menu.generate.bean.MenuInfoGenerateBean;
import cn.faury.fwmf.module.service.menu.generate.sqlProvider.MenuInfoGenerateSqlProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;
import java.util.Map;

public interface MenuInfoGenerateMapper {
    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table sys_t_menu_info
     *
     * @fwmf.generated 2018-09-26 11:34:22
     */
    @Delete({
        "delete from sys_t_menu_info",
        "where MENU_ID = #{menuId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long menuId);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table sys_t_menu_info
     *
     * @fwmf.generated 2018-09-26 11:34:22
     */
    @Insert({
        "insert into sys_t_menu_info (MENU_ID, MENU_PID, ",
        "MENU_NAME, MENU_ACTION_KEY, ",
        "MENU_CODE, IS_AVAILABLE, ",
        "IS_LEAF, SYSTEM_ID, SORT)",
        "values (#{menuId,jdbcType=BIGINT}, #{menuPid,jdbcType=BIGINT}, ",
        "#{menuName,jdbcType=VARCHAR}, #{menuActionKey,jdbcType=VARCHAR}, ",
        "#{menuCode,jdbcType=VARCHAR}, #{isAvailable,jdbcType=CHAR}, ",
        "#{isLeaf,jdbcType=CHAR}, #{systemId,jdbcType=BIGINT}, #{sort,jdbcType=INTEGER})"
    })
    @Options(useGeneratedKeys=true,keyProperty="menuId")
    int insert(MenuInfoGenerateBean record);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table sys_t_menu_info
     *
     * @fwmf.generated 2018-09-26 11:34:22
     */
    @InsertProvider(type=MenuInfoGenerateSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="menuId")
    int insertSelective(MenuInfoGenerateBean record);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table sys_t_menu_info
     *
     * @fwmf.generated 2018-09-26 11:34:22
     */
    @SelectProvider(type=MenuInfoGenerateSqlProvider.class, method="search")
    @ResultType(MenuInfoBean.class)
    List<MenuInfoBean> search(Map<String, Object> params);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table sys_t_menu_info
     *
     * @fwmf.generated 2018-09-26 11:34:22
     */
    @Select({
        "select",
        "MENU_ID, MENU_PID, MENU_NAME, MENU_ACTION_KEY, MENU_CODE, IS_AVAILABLE, IS_LEAF, ",
        "SYSTEM_ID, SORT",
        "from sys_t_menu_info",
        "where MENU_ID = #{menuId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="MENU_ID", property="menuId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="MENU_PID", property="menuPid", jdbcType=JdbcType.BIGINT),
        @Result(column="MENU_NAME", property="menuName", jdbcType=JdbcType.VARCHAR),
        @Result(column="MENU_ACTION_KEY", property="menuActionKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="MENU_CODE", property="menuCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="IS_AVAILABLE", property="isAvailable", jdbcType=JdbcType.CHAR),
        @Result(column="IS_LEAF", property="isLeaf", jdbcType=JdbcType.CHAR),
        @Result(column="SYSTEM_ID", property="systemId", jdbcType=JdbcType.BIGINT),
        @Result(column="SORT", property="sort", jdbcType=JdbcType.INTEGER)
    })
    MenuInfoBean selectByPrimaryKey(Long menuId);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table sys_t_menu_info
     *
     * @fwmf.generated 2018-09-26 11:34:22
     */
    @UpdateProvider(type=MenuInfoGenerateSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MenuInfoGenerateBean record);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table sys_t_menu_info
     *
     * @fwmf.generated 2018-09-26 11:34:22
     */
    @Update({
        "update sys_t_menu_info",
        "set MENU_PID = #{menuPid,jdbcType=BIGINT},",
          "MENU_NAME = #{menuName,jdbcType=VARCHAR},",
          "MENU_ACTION_KEY = #{menuActionKey,jdbcType=VARCHAR},",
          "MENU_CODE = #{menuCode,jdbcType=VARCHAR},",
          "IS_AVAILABLE = #{isAvailable,jdbcType=CHAR},",
          "IS_LEAF = #{isLeaf,jdbcType=CHAR},",
          "SYSTEM_ID = #{systemId,jdbcType=BIGINT},",
          "SORT = #{sort,jdbcType=INTEGER}",
        "where MENU_ID = #{menuId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(MenuInfoGenerateBean record);
}