/**
 * This file was generator by Fwmf Generated
 * ！！！Do not modify this file！！ 
 *
 * @fwmf.generated 2018-12-14 09:33:56
 */
package cn.faury.fwmf.module.service.menu.generate.mapper;

import cn.faury.fwmf.module.api.menu.bean.RoleRFunctionBean;
import cn.faury.fwmf.module.api.menu.generate.bean.RoleRFunctionGenerateBean;
import cn.faury.fwmf.module.service.menu.generate.sqlProvider.RoleRFunctionGenerateSqlProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;
import java.util.Map;

public interface RoleRFunctionGenerateMapper {
    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table sys_t_role_r_function
     *
     * @fwmf.generated 2018-12-14 09:33:56
     */
    @Delete({
        "DELETE FROM sys_t_role_r_function",
        "WHERE `ID` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table sys_t_role_r_function
     *
     * @fwmf.generated 2018-12-14 09:33:56
     */
    @Insert({
        "INSERT INTO sys_t_role_r_function (`ID`, `ROLE_ID`, ",
        "`FUNCTION_ID`)",
        "VALUES (#{id,jdbcType=BIGINT}, #{roleId,jdbcType=BIGINT}, ",
        "#{functionId,jdbcType=BIGINT})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(RoleRFunctionGenerateBean record);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table sys_t_role_r_function
     *
     * @fwmf.generated 2018-12-14 09:33:56
     */
    @InsertProvider(type=RoleRFunctionGenerateSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(RoleRFunctionGenerateBean record);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table sys_t_role_r_function
     *
     * @fwmf.generated 2018-12-14 09:33:56
     */
    @SelectProvider(type=RoleRFunctionGenerateSqlProvider.class, method="search")
    @ResultType(RoleRFunctionBean.class)
    List<RoleRFunctionBean> search(Map<String, Object> params);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table sys_t_role_r_function
     *
     * @fwmf.generated 2018-12-14 09:33:56
     */
    @Select({
        "SELECT",
        "`ID`, `ROLE_ID`, `FUNCTION_ID`",
        "FROM sys_t_role_r_function",
        "WHERE `ID` = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="ROLE_ID", property="roleId", jdbcType=JdbcType.BIGINT),
        @Result(column="FUNCTION_ID", property="functionId", jdbcType=JdbcType.BIGINT)
    })
    RoleRFunctionBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table sys_t_role_r_function
     *
     * @fwmf.generated 2018-12-14 09:33:56
     */
    @UpdateProvider(type=RoleRFunctionGenerateSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(RoleRFunctionGenerateBean record);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table sys_t_role_r_function
     *
     * @fwmf.generated 2018-12-14 09:33:56
     */
    @Update({
        "UPDATE sys_t_role_r_function",
        "SET `ROLE_ID` = #{roleId,jdbcType=BIGINT},",
          "`FUNCTION_ID` = #{functionId,jdbcType=BIGINT}",
        "WHERE `ID` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(RoleRFunctionGenerateBean record);
}