package cn.faury.fwmf.module.api.order.generate.bean;

import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order_t_order_r_goods
 */
public class OrderRGoodsGenerateBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.ORDER_R_GOODS_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private Long orderRGoodsId;

    /**
     * Database Column Remarks:
     *   订单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.ORDER_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private Long orderId;

    /**
     * Database Column Remarks:
     *   商店id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.SHOP_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private Long shopId;

    /**
     * Database Column Remarks:
     *   商铺ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.STORE_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private Long storeId;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.GOODS_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private Long goodsId;

    /**
     * Database Column Remarks:
     *   二维码code
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.TDC_CODE_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private String tdcCodeId;

    /**
     * Database Column Remarks:
     *   二维码url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.TDC_CODE_PIC_URL
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private String tdcCodePicUrl;

    /**
     * Database Column Remarks:
     *   标题图片地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.TITLE_IMG
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private String titleImg;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.GOODS_NAME
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private String goodsName;

    /**
     * Database Column Remarks:
     *   商品类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.GOODS_TYPE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private String goodsType;

    /**
     * Database Column Remarks:
     *   商品单价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.GOODS_PRICE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private BigDecimal goodsPrice;

    /**
     * Database Column Remarks:
     *   购买单价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.BUY_PRICE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private BigDecimal buyPrice;

    /**
     * Database Column Remarks:
     *   购买前商品库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.GOODS_STOCK
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private Integer goodsStock;

    /**
     * Database Column Remarks:
     *   商品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.GOODS_COUNT
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private Integer goodsCount;

    /**
     * Database Column Remarks:
     *   商品小计=BUY_PRICE * GOODS_COUNT
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.BUY_SUBTOTAL
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private BigDecimal buySubtotal;

    /**
     * Database Column Remarks:
     *   金额活动ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.PROMOTION_PRICE_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private Long promotionPriceId;

    /**
     * Database Column Remarks:
     *   金额活动名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.PROMOTION_PRICE_NAME
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private String promotionPriceName;

    /**
     * Database Column Remarks:
     *   金额活动折扣总金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.PROMOTION_PRICE_AMOUNT
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private BigDecimal promotionPriceAmount;

    /**
     * Database Column Remarks:
     *   商品支付金额=商品小计-优惠金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.GOODS_PAY_PRICE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private BigDecimal goodsPayPrice;

    /**
     * Database Column Remarks:
     *   邮费ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.POSTAGE_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private Long postageId;

    /**
     * Database Column Remarks:
     *   商品邮费
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.POST_PRICE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private BigDecimal postPrice;

    /**
     * Database Column Remarks:
     *   运费活动ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.PROMOTION_POST_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private Long promotionPostId;

    /**
     * Database Column Remarks:
     *   运费活动名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.PROMOTION_POST_NAME
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private String promotionPostName;

    /**
     * Database Column Remarks:
     *   是否领取(0：否，1：是)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.IS_RECEIVE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private String isReceive;

    /**
     * Database Column Remarks:
     *   是否已评价（1：是，0：否）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_r_goods.IS_REVIEWS
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    private String isReviews;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.ORDER_R_GOODS_ID
     *
     * @return the value of order_t_order_r_goods.ORDER_R_GOODS_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public Long getOrderRGoodsId() {
        return orderRGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.ORDER_R_GOODS_ID
     *
     * @param orderRGoodsId the value for order_t_order_r_goods.ORDER_R_GOODS_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setOrderRGoodsId(Long orderRGoodsId) {
        this.orderRGoodsId = orderRGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.ORDER_ID
     *
     * @return the value of order_t_order_r_goods.ORDER_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.ORDER_ID
     *
     * @param orderId the value for order_t_order_r_goods.ORDER_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.SHOP_ID
     *
     * @return the value of order_t_order_r_goods.SHOP_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.SHOP_ID
     *
     * @param shopId the value for order_t_order_r_goods.SHOP_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.STORE_ID
     *
     * @return the value of order_t_order_r_goods.STORE_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.STORE_ID
     *
     * @param storeId the value for order_t_order_r_goods.STORE_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.GOODS_ID
     *
     * @return the value of order_t_order_r_goods.GOODS_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.GOODS_ID
     *
     * @param goodsId the value for order_t_order_r_goods.GOODS_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.TDC_CODE_ID
     *
     * @return the value of order_t_order_r_goods.TDC_CODE_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public String getTdcCodeId() {
        return tdcCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.TDC_CODE_ID
     *
     * @param tdcCodeId the value for order_t_order_r_goods.TDC_CODE_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setTdcCodeId(String tdcCodeId) {
        this.tdcCodeId = tdcCodeId == null ? null : tdcCodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.TDC_CODE_PIC_URL
     *
     * @return the value of order_t_order_r_goods.TDC_CODE_PIC_URL
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public String getTdcCodePicUrl() {
        return tdcCodePicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.TDC_CODE_PIC_URL
     *
     * @param tdcCodePicUrl the value for order_t_order_r_goods.TDC_CODE_PIC_URL
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setTdcCodePicUrl(String tdcCodePicUrl) {
        this.tdcCodePicUrl = tdcCodePicUrl == null ? null : tdcCodePicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.TITLE_IMG
     *
     * @return the value of order_t_order_r_goods.TITLE_IMG
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public String getTitleImg() {
        return titleImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.TITLE_IMG
     *
     * @param titleImg the value for order_t_order_r_goods.TITLE_IMG
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setTitleImg(String titleImg) {
        this.titleImg = titleImg == null ? null : titleImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.GOODS_NAME
     *
     * @return the value of order_t_order_r_goods.GOODS_NAME
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.GOODS_NAME
     *
     * @param goodsName the value for order_t_order_r_goods.GOODS_NAME
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.GOODS_TYPE
     *
     * @return the value of order_t_order_r_goods.GOODS_TYPE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.GOODS_TYPE
     *
     * @param goodsType the value for order_t_order_r_goods.GOODS_TYPE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType == null ? null : goodsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.GOODS_PRICE
     *
     * @return the value of order_t_order_r_goods.GOODS_PRICE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.GOODS_PRICE
     *
     * @param goodsPrice the value for order_t_order_r_goods.GOODS_PRICE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.BUY_PRICE
     *
     * @return the value of order_t_order_r_goods.BUY_PRICE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public BigDecimal getBuyPrice() {
        return buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.BUY_PRICE
     *
     * @param buyPrice the value for order_t_order_r_goods.BUY_PRICE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setBuyPrice(BigDecimal buyPrice) {
        this.buyPrice = buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.GOODS_STOCK
     *
     * @return the value of order_t_order_r_goods.GOODS_STOCK
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public Integer getGoodsStock() {
        return goodsStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.GOODS_STOCK
     *
     * @param goodsStock the value for order_t_order_r_goods.GOODS_STOCK
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setGoodsStock(Integer goodsStock) {
        this.goodsStock = goodsStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.GOODS_COUNT
     *
     * @return the value of order_t_order_r_goods.GOODS_COUNT
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.GOODS_COUNT
     *
     * @param goodsCount the value for order_t_order_r_goods.GOODS_COUNT
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.BUY_SUBTOTAL
     *
     * @return the value of order_t_order_r_goods.BUY_SUBTOTAL
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public BigDecimal getBuySubtotal() {
        return buySubtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.BUY_SUBTOTAL
     *
     * @param buySubtotal the value for order_t_order_r_goods.BUY_SUBTOTAL
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setBuySubtotal(BigDecimal buySubtotal) {
        this.buySubtotal = buySubtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.PROMOTION_PRICE_ID
     *
     * @return the value of order_t_order_r_goods.PROMOTION_PRICE_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public Long getPromotionPriceId() {
        return promotionPriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.PROMOTION_PRICE_ID
     *
     * @param promotionPriceId the value for order_t_order_r_goods.PROMOTION_PRICE_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setPromotionPriceId(Long promotionPriceId) {
        this.promotionPriceId = promotionPriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.PROMOTION_PRICE_NAME
     *
     * @return the value of order_t_order_r_goods.PROMOTION_PRICE_NAME
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public String getPromotionPriceName() {
        return promotionPriceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.PROMOTION_PRICE_NAME
     *
     * @param promotionPriceName the value for order_t_order_r_goods.PROMOTION_PRICE_NAME
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setPromotionPriceName(String promotionPriceName) {
        this.promotionPriceName = promotionPriceName == null ? null : promotionPriceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.PROMOTION_PRICE_AMOUNT
     *
     * @return the value of order_t_order_r_goods.PROMOTION_PRICE_AMOUNT
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public BigDecimal getPromotionPriceAmount() {
        return promotionPriceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.PROMOTION_PRICE_AMOUNT
     *
     * @param promotionPriceAmount the value for order_t_order_r_goods.PROMOTION_PRICE_AMOUNT
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setPromotionPriceAmount(BigDecimal promotionPriceAmount) {
        this.promotionPriceAmount = promotionPriceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.GOODS_PAY_PRICE
     *
     * @return the value of order_t_order_r_goods.GOODS_PAY_PRICE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public BigDecimal getGoodsPayPrice() {
        return goodsPayPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.GOODS_PAY_PRICE
     *
     * @param goodsPayPrice the value for order_t_order_r_goods.GOODS_PAY_PRICE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setGoodsPayPrice(BigDecimal goodsPayPrice) {
        this.goodsPayPrice = goodsPayPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.POSTAGE_ID
     *
     * @return the value of order_t_order_r_goods.POSTAGE_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public Long getPostageId() {
        return postageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.POSTAGE_ID
     *
     * @param postageId the value for order_t_order_r_goods.POSTAGE_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setPostageId(Long postageId) {
        this.postageId = postageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.POST_PRICE
     *
     * @return the value of order_t_order_r_goods.POST_PRICE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public BigDecimal getPostPrice() {
        return postPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.POST_PRICE
     *
     * @param postPrice the value for order_t_order_r_goods.POST_PRICE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setPostPrice(BigDecimal postPrice) {
        this.postPrice = postPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.PROMOTION_POST_ID
     *
     * @return the value of order_t_order_r_goods.PROMOTION_POST_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public Long getPromotionPostId() {
        return promotionPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.PROMOTION_POST_ID
     *
     * @param promotionPostId the value for order_t_order_r_goods.PROMOTION_POST_ID
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setPromotionPostId(Long promotionPostId) {
        this.promotionPostId = promotionPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.PROMOTION_POST_NAME
     *
     * @return the value of order_t_order_r_goods.PROMOTION_POST_NAME
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public String getPromotionPostName() {
        return promotionPostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.PROMOTION_POST_NAME
     *
     * @param promotionPostName the value for order_t_order_r_goods.PROMOTION_POST_NAME
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setPromotionPostName(String promotionPostName) {
        this.promotionPostName = promotionPostName == null ? null : promotionPostName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.IS_RECEIVE
     *
     * @return the value of order_t_order_r_goods.IS_RECEIVE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public String getIsReceive() {
        return isReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.IS_RECEIVE
     *
     * @param isReceive the value for order_t_order_r_goods.IS_RECEIVE
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setIsReceive(String isReceive) {
        this.isReceive = isReceive == null ? null : isReceive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_r_goods.IS_REVIEWS
     *
     * @return the value of order_t_order_r_goods.IS_REVIEWS
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public String getIsReviews() {
        return isReviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_r_goods.IS_REVIEWS
     *
     * @param isReviews the value for order_t_order_r_goods.IS_REVIEWS
     *
     * @mbg.generated Sun Aug 05 14:35:53 CST 2018
     */
    public void setIsReviews(String isReviews) {
        this.isReviews = isReviews == null ? null : isReviews.trim();
    }
}