package cn.faury.fwmf.module.api.order.generate.bean;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order_t_order_pay_info
 */
public class OrderPayInfoGenerateBean {
    /**
     * Database Column Remarks:
     *   唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_pay_info.ID
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   订单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_pay_info.ORDER_ID
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    private Long orderId;

    /**
     * Database Column Remarks:
     *   付款金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_pay_info.PAY_AMOUNT
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    private BigDecimal payAmount;

    /**
     * Database Column Remarks:
     *   状态(1：待支付、2：已支付、3：已取消)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_pay_info.PAY_STATE
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    private String payState;

    /**
     * Database Column Remarks:
     *   付款时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_pay_info.PAY_TIME
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    private Date payTime;

    /**
     * Database Column Remarks:
     *   付款来源（虚拟币、支付宝、微信等)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_pay_info.PAY_STYLE
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    private String payStyle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_pay_info.CREATE_PERSON
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    private Long createPerson;

    /**
     * Database Column Remarks:
     *   创建者姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_pay_info.CREATE_PERSON_NAME
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    private String createPersonName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_pay_info.CREATE_TIME
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_pay_info.UPDATE_PERSON
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    private Long updatePerson;

    /**
     * Database Column Remarks:
     *   更新者姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_pay_info.UPDATE_PERSON_NAME
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    private String updatePersonName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_pay_info.UPDATE_TIME
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   对账状态(1:对账成功)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_order_pay_info.DZ_STATE
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    private Integer dzState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_pay_info.ID
     *
     * @return the value of order_t_order_pay_info.ID
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_pay_info.ID
     *
     * @param id the value for order_t_order_pay_info.ID
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_pay_info.ORDER_ID
     *
     * @return the value of order_t_order_pay_info.ORDER_ID
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_pay_info.ORDER_ID
     *
     * @param orderId the value for order_t_order_pay_info.ORDER_ID
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_pay_info.PAY_AMOUNT
     *
     * @return the value of order_t_order_pay_info.PAY_AMOUNT
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_pay_info.PAY_AMOUNT
     *
     * @param payAmount the value for order_t_order_pay_info.PAY_AMOUNT
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_pay_info.PAY_STATE
     *
     * @return the value of order_t_order_pay_info.PAY_STATE
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public String getPayState() {
        return payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_pay_info.PAY_STATE
     *
     * @param payState the value for order_t_order_pay_info.PAY_STATE
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public void setPayState(String payState) {
        this.payState = payState == null ? null : payState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_pay_info.PAY_TIME
     *
     * @return the value of order_t_order_pay_info.PAY_TIME
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_pay_info.PAY_TIME
     *
     * @param payTime the value for order_t_order_pay_info.PAY_TIME
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_pay_info.PAY_STYLE
     *
     * @return the value of order_t_order_pay_info.PAY_STYLE
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public String getPayStyle() {
        return payStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_pay_info.PAY_STYLE
     *
     * @param payStyle the value for order_t_order_pay_info.PAY_STYLE
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public void setPayStyle(String payStyle) {
        this.payStyle = payStyle == null ? null : payStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_pay_info.CREATE_PERSON
     *
     * @return the value of order_t_order_pay_info.CREATE_PERSON
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public Long getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_pay_info.CREATE_PERSON
     *
     * @param createPerson the value for order_t_order_pay_info.CREATE_PERSON
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public void setCreatePerson(Long createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_pay_info.CREATE_PERSON_NAME
     *
     * @return the value of order_t_order_pay_info.CREATE_PERSON_NAME
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public String getCreatePersonName() {
        return createPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_pay_info.CREATE_PERSON_NAME
     *
     * @param createPersonName the value for order_t_order_pay_info.CREATE_PERSON_NAME
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public void setCreatePersonName(String createPersonName) {
        this.createPersonName = createPersonName == null ? null : createPersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_pay_info.CREATE_TIME
     *
     * @return the value of order_t_order_pay_info.CREATE_TIME
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_pay_info.CREATE_TIME
     *
     * @param createTime the value for order_t_order_pay_info.CREATE_TIME
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_pay_info.UPDATE_PERSON
     *
     * @return the value of order_t_order_pay_info.UPDATE_PERSON
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public Long getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_pay_info.UPDATE_PERSON
     *
     * @param updatePerson the value for order_t_order_pay_info.UPDATE_PERSON
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public void setUpdatePerson(Long updatePerson) {
        this.updatePerson = updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_pay_info.UPDATE_PERSON_NAME
     *
     * @return the value of order_t_order_pay_info.UPDATE_PERSON_NAME
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public String getUpdatePersonName() {
        return updatePersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_pay_info.UPDATE_PERSON_NAME
     *
     * @param updatePersonName the value for order_t_order_pay_info.UPDATE_PERSON_NAME
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public void setUpdatePersonName(String updatePersonName) {
        this.updatePersonName = updatePersonName == null ? null : updatePersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_pay_info.UPDATE_TIME
     *
     * @return the value of order_t_order_pay_info.UPDATE_TIME
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_pay_info.UPDATE_TIME
     *
     * @param updateTime the value for order_t_order_pay_info.UPDATE_TIME
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_order_pay_info.DZ_STATE
     *
     * @return the value of order_t_order_pay_info.DZ_STATE
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public Integer getDzState() {
        return dzState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_order_pay_info.DZ_STATE
     *
     * @param dzState the value for order_t_order_pay_info.DZ_STATE
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    public void setDzState(Integer dzState) {
        this.dzState = dzState;
    }
}