/**
 * This file was generator by Fwmf Generated
 * ！！！Do not modify this file！！ 
 *
 * @fwmf.generated 2018-12-08 15:12:42
 */
package cn.faury.fwmf.module.api.order.generate.bean;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   套餐基本信息表
 *
 * This class was generated by Fwmf Generated.
 * This class corresponds to the database table order_t_package_info
 *
 * @fwmf.generated 2018-12-08 15:12:42
 */
public class PackageInfoGenerateBean {
    /**
     * Database Column Remarks:
     *   图书ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column order_t_package_info.PACKAGE_ID
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    private Long packageId;

    /**
     * Database Column Remarks:
     *   套餐名称
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column order_t_package_info.PACKAGE_NAME
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    private String packageName;

    /**
     * Database Column Remarks:
     *   套餐价格
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column order_t_package_info.PACKAGE_PRICE
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    private BigDecimal packagePrice;

    /**
     * Database Column Remarks:
     *   商店ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column order_t_package_info.SHOP_ID
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    private Long shopId;

    /**
     * Database Column Remarks:
     *   商铺ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column order_t_package_info.STORE_ID
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    private Long storeId;

    /**
     * Database Column Remarks:
     *   运费ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column order_t_package_info.POSTAGE_ID
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    private Long postageId;

    /**
     * Database Column Remarks:
     *   是否删除(Y是  N否)
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column order_t_package_info.IS_DELETE
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    private String isDelete;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column order_t_package_info.CREATE_PERSON
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    private Long createPerson;

    /**
     * Database Column Remarks:
     *   创建人姓名
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column order_t_package_info.CREATE_PERSON_NAME
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    private String createPersonName;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column order_t_package_info.CREATE_TIME
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改人ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column order_t_package_info.UPDATE_PERSON
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    private Long updatePerson;

    /**
     * Database Column Remarks:
     *   修改人姓名
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column order_t_package_info.UPDATE_PERSON_NAME
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    private String updatePersonName;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column order_t_package_info.UPDATE_TIME
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    private Date updateTime;

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column order_t_package_info.PACKAGE_ID
     *
     * @return the value of order_t_package_info.PACKAGE_ID
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public Long getPackageId() {
        return packageId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column order_t_package_info.PACKAGE_ID
     *
     * @param packageId the value for order_t_package_info.PACKAGE_ID
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public void setPackageId(Long packageId) {
        this.packageId = packageId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column order_t_package_info.PACKAGE_NAME
     *
     * @return the value of order_t_package_info.PACKAGE_NAME
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column order_t_package_info.PACKAGE_NAME
     *
     * @param packageName the value for order_t_package_info.PACKAGE_NAME
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName == null ? null : packageName.trim();
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column order_t_package_info.PACKAGE_PRICE
     *
     * @return the value of order_t_package_info.PACKAGE_PRICE
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public BigDecimal getPackagePrice() {
        return packagePrice;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column order_t_package_info.PACKAGE_PRICE
     *
     * @param packagePrice the value for order_t_package_info.PACKAGE_PRICE
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public void setPackagePrice(BigDecimal packagePrice) {
        this.packagePrice = packagePrice;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column order_t_package_info.SHOP_ID
     *
     * @return the value of order_t_package_info.SHOP_ID
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column order_t_package_info.SHOP_ID
     *
     * @param shopId the value for order_t_package_info.SHOP_ID
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column order_t_package_info.STORE_ID
     *
     * @return the value of order_t_package_info.STORE_ID
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column order_t_package_info.STORE_ID
     *
     * @param storeId the value for order_t_package_info.STORE_ID
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column order_t_package_info.POSTAGE_ID
     *
     * @return the value of order_t_package_info.POSTAGE_ID
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public Long getPostageId() {
        return postageId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column order_t_package_info.POSTAGE_ID
     *
     * @param postageId the value for order_t_package_info.POSTAGE_ID
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public void setPostageId(Long postageId) {
        this.postageId = postageId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column order_t_package_info.IS_DELETE
     *
     * @return the value of order_t_package_info.IS_DELETE
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column order_t_package_info.IS_DELETE
     *
     * @param isDelete the value for order_t_package_info.IS_DELETE
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column order_t_package_info.CREATE_PERSON
     *
     * @return the value of order_t_package_info.CREATE_PERSON
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public Long getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column order_t_package_info.CREATE_PERSON
     *
     * @param createPerson the value for order_t_package_info.CREATE_PERSON
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public void setCreatePerson(Long createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column order_t_package_info.CREATE_PERSON_NAME
     *
     * @return the value of order_t_package_info.CREATE_PERSON_NAME
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public String getCreatePersonName() {
        return createPersonName;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column order_t_package_info.CREATE_PERSON_NAME
     *
     * @param createPersonName the value for order_t_package_info.CREATE_PERSON_NAME
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public void setCreatePersonName(String createPersonName) {
        this.createPersonName = createPersonName == null ? null : createPersonName.trim();
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column order_t_package_info.CREATE_TIME
     *
     * @return the value of order_t_package_info.CREATE_TIME
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column order_t_package_info.CREATE_TIME
     *
     * @param createTime the value for order_t_package_info.CREATE_TIME
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column order_t_package_info.UPDATE_PERSON
     *
     * @return the value of order_t_package_info.UPDATE_PERSON
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public Long getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column order_t_package_info.UPDATE_PERSON
     *
     * @param updatePerson the value for order_t_package_info.UPDATE_PERSON
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public void setUpdatePerson(Long updatePerson) {
        this.updatePerson = updatePerson;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column order_t_package_info.UPDATE_PERSON_NAME
     *
     * @return the value of order_t_package_info.UPDATE_PERSON_NAME
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public String getUpdatePersonName() {
        return updatePersonName;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column order_t_package_info.UPDATE_PERSON_NAME
     *
     * @param updatePersonName the value for order_t_package_info.UPDATE_PERSON_NAME
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public void setUpdatePersonName(String updatePersonName) {
        this.updatePersonName = updatePersonName == null ? null : updatePersonName.trim();
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column order_t_package_info.UPDATE_TIME
     *
     * @return the value of order_t_package_info.UPDATE_TIME
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column order_t_package_info.UPDATE_TIME
     *
     * @param updateTime the value for order_t_package_info.UPDATE_TIME
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}