package cn.faury.fwmf.module.api.order.generate.bean;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order_t_promotion_info
 */
public class PromotionInfoGenerateBean {
    /**
     * Database Column Remarks:
     *   活动ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_promotion_info.PROMOTION_ID
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    private Long promotionId;

    /**
     * Database Column Remarks:
     *   活动名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_promotion_info.PROMOTION_NAME
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    private String promotionName;

    /**
     * Database Column Remarks:
     *   活动对象（00：商品价格  01：订单运费）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_promotion_info.PROMOTION_SUBJECT
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    private String promotionSubject;

    /**
     * Database Column Remarks:
     *   活动条件：00数量型 01金额型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_promotion_info.PROMOTION_CONDITION
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    private String promotionCondition;

    /**
     * Database Column Remarks:
     *   活动条件临界值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_promotion_info.CONDITION_VALUE
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    private BigDecimal conditionValue;

    /**
     * Database Column Remarks:
     *   条件达到后处理方式(set:设值,免邮之类的  discount:折扣 subtract：满减)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_promotion_info.MEET_OPERATION
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    private String meetOperation;

    /**
     * Database Column Remarks:
     *   条件达到后操作用值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_promotion_info.MEET_VALUE
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    private BigDecimal meetValue;

    /**
     * Database Column Remarks:
     *   活动开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_promotion_info.PROMOTION_START_TIME
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    private Date promotionStartTime;

    /**
     * Database Column Remarks:
     *   活动结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_promotion_info.PROMOTION_END_TIME
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    private Date promotionEndTime;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_promotion_info.CREATE_PERSON
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    private String createPerson;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_promotion_info.CREATE_TIME
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_promotion_info.UPDATE_PERSON
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    private String updatePerson;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_t_promotion_info.UPDATE_TIME
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_promotion_info.PROMOTION_ID
     *
     * @return the value of order_t_promotion_info.PROMOTION_ID
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public Long getPromotionId() {
        return promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_promotion_info.PROMOTION_ID
     *
     * @param promotionId the value for order_t_promotion_info.PROMOTION_ID
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public void setPromotionId(Long promotionId) {
        this.promotionId = promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_promotion_info.PROMOTION_NAME
     *
     * @return the value of order_t_promotion_info.PROMOTION_NAME
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public String getPromotionName() {
        return promotionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_promotion_info.PROMOTION_NAME
     *
     * @param promotionName the value for order_t_promotion_info.PROMOTION_NAME
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public void setPromotionName(String promotionName) {
        this.promotionName = promotionName == null ? null : promotionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_promotion_info.PROMOTION_SUBJECT
     *
     * @return the value of order_t_promotion_info.PROMOTION_SUBJECT
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public String getPromotionSubject() {
        return promotionSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_promotion_info.PROMOTION_SUBJECT
     *
     * @param promotionSubject the value for order_t_promotion_info.PROMOTION_SUBJECT
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public void setPromotionSubject(String promotionSubject) {
        this.promotionSubject = promotionSubject == null ? null : promotionSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_promotion_info.PROMOTION_CONDITION
     *
     * @return the value of order_t_promotion_info.PROMOTION_CONDITION
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public String getPromotionCondition() {
        return promotionCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_promotion_info.PROMOTION_CONDITION
     *
     * @param promotionCondition the value for order_t_promotion_info.PROMOTION_CONDITION
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public void setPromotionCondition(String promotionCondition) {
        this.promotionCondition = promotionCondition == null ? null : promotionCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_promotion_info.CONDITION_VALUE
     *
     * @return the value of order_t_promotion_info.CONDITION_VALUE
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public BigDecimal getConditionValue() {
        return conditionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_promotion_info.CONDITION_VALUE
     *
     * @param conditionValue the value for order_t_promotion_info.CONDITION_VALUE
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public void setConditionValue(BigDecimal conditionValue) {
        this.conditionValue = conditionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_promotion_info.MEET_OPERATION
     *
     * @return the value of order_t_promotion_info.MEET_OPERATION
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public String getMeetOperation() {
        return meetOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_promotion_info.MEET_OPERATION
     *
     * @param meetOperation the value for order_t_promotion_info.MEET_OPERATION
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public void setMeetOperation(String meetOperation) {
        this.meetOperation = meetOperation == null ? null : meetOperation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_promotion_info.MEET_VALUE
     *
     * @return the value of order_t_promotion_info.MEET_VALUE
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public BigDecimal getMeetValue() {
        return meetValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_promotion_info.MEET_VALUE
     *
     * @param meetValue the value for order_t_promotion_info.MEET_VALUE
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public void setMeetValue(BigDecimal meetValue) {
        this.meetValue = meetValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_promotion_info.PROMOTION_START_TIME
     *
     * @return the value of order_t_promotion_info.PROMOTION_START_TIME
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public Date getPromotionStartTime() {
        return promotionStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_promotion_info.PROMOTION_START_TIME
     *
     * @param promotionStartTime the value for order_t_promotion_info.PROMOTION_START_TIME
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public void setPromotionStartTime(Date promotionStartTime) {
        this.promotionStartTime = promotionStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_promotion_info.PROMOTION_END_TIME
     *
     * @return the value of order_t_promotion_info.PROMOTION_END_TIME
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public Date getPromotionEndTime() {
        return promotionEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_promotion_info.PROMOTION_END_TIME
     *
     * @param promotionEndTime the value for order_t_promotion_info.PROMOTION_END_TIME
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public void setPromotionEndTime(Date promotionEndTime) {
        this.promotionEndTime = promotionEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_promotion_info.CREATE_PERSON
     *
     * @return the value of order_t_promotion_info.CREATE_PERSON
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_promotion_info.CREATE_PERSON
     *
     * @param createPerson the value for order_t_promotion_info.CREATE_PERSON
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_promotion_info.CREATE_TIME
     *
     * @return the value of order_t_promotion_info.CREATE_TIME
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_promotion_info.CREATE_TIME
     *
     * @param createTime the value for order_t_promotion_info.CREATE_TIME
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_promotion_info.UPDATE_PERSON
     *
     * @return the value of order_t_promotion_info.UPDATE_PERSON
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_promotion_info.UPDATE_PERSON
     *
     * @param updatePerson the value for order_t_promotion_info.UPDATE_PERSON
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson == null ? null : updatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_t_promotion_info.UPDATE_TIME
     *
     * @return the value of order_t_promotion_info.UPDATE_TIME
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_t_promotion_info.UPDATE_TIME
     *
     * @param updateTime the value for order_t_promotion_info.UPDATE_TIME
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}