/**
 * This file was generator by Fwmf Generated
 * @fwmf.generated 2018-08-18 22:31:52
 */
package cn.faury.fwmf.module.service.school.generate.mapper;

import cn.faury.fwmf.module.api.school.generate.bean.SchoolInfoGenerateBean;
import org.apache.ibatis.jdbc.SQL;

public class SchoolInfoGenerateSqlProvider {

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database tablesys_t_school_info
     *
     * @fwmf.generated 2018-08-18 22:31:52
     */
    public String insertSelective(SchoolInfoGenerateBean record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("sys_t_school_info");
        
        if (record.getSchoolName() != null) {
            sql.VALUES("SCHOOL_NAME", "#{schoolName,jdbcType=VARCHAR}");
        }
        
        if (record.getSchoolShortname() != null) {
            sql.VALUES("SCHOOL_SHORTNAME", "#{schoolShortname,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaCodeProvince() != null) {
            sql.VALUES("AREA_CODE_PROVINCE", "#{areaCodeProvince,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaDescProvince() != null) {
            sql.VALUES("AREA_DESC_PROVINCE", "#{areaDescProvince,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaCodeCity() != null) {
            sql.VALUES("AREA_CODE_CITY", "#{areaCodeCity,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaDescCity() != null) {
            sql.VALUES("AREA_DESC_CITY", "#{areaDescCity,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaCodeCounty() != null) {
            sql.VALUES("AREA_CODE_COUNTY", "#{areaCodeCounty,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaDescCounty() != null) {
            sql.VALUES("AREA_DESC_COUNTY", "#{areaDescCounty,jdbcType=VARCHAR}");
        }
        
        if (record.getContactName() != null) {
            sql.VALUES("CONTACT_NAME", "#{contactName,jdbcType=VARCHAR}");
        }
        
        if (record.getTelNo() != null) {
            sql.VALUES("TEL_NO", "#{telNo,jdbcType=VARCHAR}");
        }
        
        if (record.getAddress() != null) {
            sql.VALUES("ADDRESS", "#{address,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDelete() != null) {
            sql.VALUES("IS_DELETE", "#{isDelete,jdbcType=CHAR}");
        }
        
        if (record.getPkg() != null) {
            sql.VALUES("PKG", "#{pkg,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatePerson() != null) {
            sql.VALUES("CREATE_PERSON", "#{createPerson,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("CREATE_TIME", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatePerson() != null) {
            sql.VALUES("UPDATE_PERSON", "#{updatePerson,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("UPDATE_TIME", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSchoolLevel() != null) {
            sql.VALUES("SCHOOL_LEVEL", "#{schoolLevel,jdbcType=CHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database tablesys_t_school_info
     *
     * @fwmf.generated 2018-08-18 22:31:52
     */
    public String updateByPrimaryKeySelective(SchoolInfoGenerateBean record) {
        SQL sql = new SQL();
        sql.UPDATE("sys_t_school_info");
        
        if (record.getSchoolName() != null) {
            sql.SET("SCHOOL_NAME = #{schoolName,jdbcType=VARCHAR}");
        }
        
        if (record.getSchoolShortname() != null) {
            sql.SET("SCHOOL_SHORTNAME = #{schoolShortname,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaCodeProvince() != null) {
            sql.SET("AREA_CODE_PROVINCE = #{areaCodeProvince,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaDescProvince() != null) {
            sql.SET("AREA_DESC_PROVINCE = #{areaDescProvince,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaCodeCity() != null) {
            sql.SET("AREA_CODE_CITY = #{areaCodeCity,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaDescCity() != null) {
            sql.SET("AREA_DESC_CITY = #{areaDescCity,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaCodeCounty() != null) {
            sql.SET("AREA_CODE_COUNTY = #{areaCodeCounty,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaDescCounty() != null) {
            sql.SET("AREA_DESC_COUNTY = #{areaDescCounty,jdbcType=VARCHAR}");
        }
        
        if (record.getContactName() != null) {
            sql.SET("CONTACT_NAME = #{contactName,jdbcType=VARCHAR}");
        }
        
        if (record.getTelNo() != null) {
            sql.SET("TEL_NO = #{telNo,jdbcType=VARCHAR}");
        }
        
        if (record.getAddress() != null) {
            sql.SET("ADDRESS = #{address,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDelete() != null) {
            sql.SET("IS_DELETE = #{isDelete,jdbcType=CHAR}");
        }
        
        if (record.getPkg() != null) {
            sql.SET("PKG = #{pkg,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatePerson() != null) {
            sql.SET("CREATE_PERSON = #{createPerson,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("CREATE_TIME = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatePerson() != null) {
            sql.SET("UPDATE_PERSON = #{updatePerson,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSchoolLevel() != null) {
            sql.SET("SCHOOL_LEVEL = #{schoolLevel,jdbcType=CHAR}");
        }
        
        sql.WHERE("SCHOOL_ID = #{schoolId,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}