/**
 * This file was generator by Fwmf Generated
 * ！！！Do not modify this file！！ 
 *
 * @fwmf.generated 2018-11-14 17:14:30
 */
package cn.faury.fwmf.module.service.category.generate.sqlProvider;

import cn.faury.fdk.common.utils.StringUtil;
import cn.faury.fwmf.module.api.category.generate.bean.TagInfoGenerateBean;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TagInfoGenerateSqlProvider {

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table product_t_tag_info
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    public String insertSelective(TagInfoGenerateBean record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("product_t_tag_info");
        
        if (record.getTagId() != null) {
            sql.VALUES("TAG_ID", "#{tagId,jdbcType=BIGINT}");
        }
        
        if (record.getTagCode() != null) {
            sql.VALUES("TAG_CODE", "#{tagCode,jdbcType=VARCHAR}");
        }
        
        if (record.getTagValue() != null) {
            sql.VALUES("TAG_VALUE", "#{tagValue,jdbcType=VARCHAR}");
        }
        
        if (record.getTagType() != null) {
            sql.VALUES("TAG_TYPE", "#{tagType,jdbcType=CHAR}");
        }
        
        if (record.getDisplayOrder() != null) {
            sql.VALUES("DISPLAY_ORDER", "#{displayOrder,jdbcType=INTEGER}");
        }
        
        if (record.getParentId() != null) {
            sql.VALUES("PARENT_ID", "#{parentId,jdbcType=BIGINT}");
        }
        
        if (record.getXpath() != null) {
            sql.VALUES("XPATH", "#{xpath,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDelete() != null) {
            sql.VALUES("IS_DELETE", "#{isDelete,jdbcType=CHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table product_t_tag_info
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    public String updateByPrimaryKeySelective(TagInfoGenerateBean record) {
        SQL sql = new SQL();
        sql.UPDATE("product_t_tag_info");
        
        if (record.getTagCode() != null) {
            sql.SET("TAG_CODE = #{tagCode,jdbcType=VARCHAR}");
        }
        
        if (record.getTagValue() != null) {
            sql.SET("TAG_VALUE = #{tagValue,jdbcType=VARCHAR}");
        }
        
        if (record.getTagType() != null) {
            sql.SET("TAG_TYPE = #{tagType,jdbcType=CHAR}");
        }
        
        if (record.getDisplayOrder() != null) {
            sql.SET("DISPLAY_ORDER = #{displayOrder,jdbcType=INTEGER}");
        }
        
        if (record.getParentId() != null) {
            sql.SET("PARENT_ID = #{parentId,jdbcType=BIGINT}");
        }
        
        if (record.getXpath() != null) {
            sql.SET("XPATH = #{xpath,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDelete() != null) {
            sql.SET("IS_DELETE = #{isDelete,jdbcType=CHAR}");
        }
        
        sql.WHERE("TAG_ID = #{tagId,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table product_t_tag_info
     *
     * @fwmf.generated 2018-11-14 17:14:30
     */
    public String search(Map<String, Object> params) {
        SQL sql = new SQL();
        sql.SELECT("TAG_ID, TAG_CODE, TAG_VALUE, TAG_TYPE, DISPLAY_ORDER, PARENT_ID, XPATH, IS_DELETE");
        
        sql.FROM("product_t_tag_info");
        
        if (params.get("tagId") != null){
            if (!(params.get("tagId") instanceof String) || StringUtil.isNotEmpty((String) params.get("tagId"))){
                sql.WHERE("TAG_ID=#{tagId,jdbcType=BIGINT}");
            }
        }
        if (params.get("ids") != null && params.get("ids") instanceof List) {
            List list = (List) params.get("ids");
            if (list != null && list.size() > 0) {
                StringBuilder inClause = new StringBuilder();
                for (int i = 0; i < list.size(); i++) {
                    inClause.append("#{ids[").append(i).append("],jdbcType=BIGINT},");
                }
                inClause.setLength(inClause.length() - 1);
                sql.WHERE("TAG_ID IN (" + inClause.toString() + ")");
            }
        }
        if (params.get("tagCode") != null){
            if (!(params.get("tagCode") instanceof String) || StringUtil.isNotEmpty((String) params.get("tagCode"))){
                sql.WHERE("TAG_CODE=#{tagCode,jdbcType=VARCHAR}");
            }
        }
        if (params.get("tagCodeLike")!=null){
            if (!(params.get("tagCodeLike") instanceof String) || StringUtil.isNotEmpty((String) params.get("tagCodeLike"))){
                sql.WHERE("TAG_CODE LIKE CONCAT('%',#{tagCodeLike,jdbcType=VARCHAR},'%')");
            }
        }
        if (params.get("tagValue") != null){
            if (!(params.get("tagValue") instanceof String) || StringUtil.isNotEmpty((String) params.get("tagValue"))){
                sql.WHERE("TAG_VALUE=#{tagValue,jdbcType=VARCHAR}");
            }
        }
        if (params.get("tagValueLike")!=null){
            if (!(params.get("tagValueLike") instanceof String) || StringUtil.isNotEmpty((String) params.get("tagValueLike"))){
                sql.WHERE("TAG_VALUE LIKE CONCAT('%',#{tagValueLike,jdbcType=VARCHAR},'%')");
            }
        }
        if (params.get("tagType") != null){
            if (!(params.get("tagType") instanceof String) || StringUtil.isNotEmpty((String) params.get("tagType"))){
                sql.WHERE("TAG_TYPE=#{tagType,jdbcType=CHAR}");
            }
        }
        if (params.get("tagTypeLike")!=null){
            if (!(params.get("tagTypeLike") instanceof String) || StringUtil.isNotEmpty((String) params.get("tagTypeLike"))){
                sql.WHERE("TAG_TYPE LIKE CONCAT('%',#{tagTypeLike,jdbcType=CHAR},'%')");
            }
        }
        if (params.get("displayOrder") != null){
            if (!(params.get("displayOrder") instanceof String) || StringUtil.isNotEmpty((String) params.get("displayOrder"))){
                sql.WHERE("DISPLAY_ORDER=#{displayOrder,jdbcType=INTEGER}");
            }
        }
        if (params.get("parentId") != null){
            if (!(params.get("parentId") instanceof String) || StringUtil.isNotEmpty((String) params.get("parentId"))){
                sql.WHERE("PARENT_ID=#{parentId,jdbcType=BIGINT}");
            }
        }
        if (params.get("xpath") != null){
            if (!(params.get("xpath") instanceof String) || StringUtil.isNotEmpty((String) params.get("xpath"))){
                sql.WHERE("XPATH=#{xpath,jdbcType=VARCHAR}");
            }
        }
        if (params.get("xpathLike")!=null){
            if (!(params.get("xpathLike") instanceof String) || StringUtil.isNotEmpty((String) params.get("xpathLike"))){
                sql.WHERE("XPATH LIKE CONCAT('%',#{xpathLike,jdbcType=VARCHAR},'%')");
            }
        }
        if (params.get("isDelete") != null){
            if (!(params.get("isDelete") instanceof String) || StringUtil.isNotEmpty((String) params.get("isDelete"))){
                sql.WHERE("IS_DELETE=#{isDelete,jdbcType=CHAR}");
            }
        }
        if (params.get("isDeleteLike")!=null){
            if (!(params.get("isDeleteLike") instanceof String) || StringUtil.isNotEmpty((String) params.get("isDeleteLike"))){
                sql.WHERE("IS_DELETE LIKE CONCAT('%',#{isDeleteLike,jdbcType=CHAR},'%')");
            }
        }
        if (params.get("ORDER_BY") != null){
            String orderBy = (String) params.get("ORDER_BY");
            String[] columns = orderBy.split(",");
            for (int i = 0; i < columns.length; i = i + 2) {
                if (i+1<columns.length){
                    sql.ORDER_BY(String.format("%s %s",columns[i],columns[i+1]));
                } else {
                    sql.ORDER_BY(columns[i]);
                }
            }
        }
        
        return sql.toString();
    }
}