/**
 * This file was generator by Fwmf Generated
 * ！！！Do not modify this file！！ 
 *
 * @fwmf.generated 2018-09-21 17:22:30
 */
package cn.faury.fwmf.module.api.role.generate.bean;

/**
 * Database Table Remarks:
 *   用户关联角色表
 *
 * This class was generated by Fwmf Generated.
 * This class corresponds to the database table sys_t_user_r_role
 *
 * @fwmf.generated 2018-09-21 17:22:30
 */
public class UserRRoleGenerateBean {
    /**
     * Database Column Remarks:
     *   唯一主键
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column sys_t_user_r_role.ID
     *
     * @fwmf.generated 2018-09-21 17:22:30
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column sys_t_user_r_role.USER_ID
     *
     * @fwmf.generated 2018-09-21 17:22:30
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   角色ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column sys_t_user_r_role.ROLE_ID
     *
     * @fwmf.generated 2018-09-21 17:22:30
     */
    private Long roleId;

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column sys_t_user_r_role.ID
     *
     * @return the value of sys_t_user_r_role.ID
     *
     * @fwmf.generated 2018-09-21 17:22:30
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column sys_t_user_r_role.ID
     *
     * @param id the value for sys_t_user_r_role.ID
     *
     * @fwmf.generated 2018-09-21 17:22:30
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column sys_t_user_r_role.USER_ID
     *
     * @return the value of sys_t_user_r_role.USER_ID
     *
     * @fwmf.generated 2018-09-21 17:22:30
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column sys_t_user_r_role.USER_ID
     *
     * @param userId the value for sys_t_user_r_role.USER_ID
     *
     * @fwmf.generated 2018-09-21 17:22:30
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column sys_t_user_r_role.ROLE_ID
     *
     * @return the value of sys_t_user_r_role.ROLE_ID
     *
     * @fwmf.generated 2018-09-21 17:22:30
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column sys_t_user_r_role.ROLE_ID
     *
     * @param roleId the value for sys_t_user_r_role.ROLE_ID
     *
     * @fwmf.generated 2018-09-21 17:22:30
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}