/**
 * This file was generator by Fwmf Generated
 * @fwmf.generated 2018-08-18 22:31:52
 */
package cn.faury.fwmf.module.api.school.generate.bean;

/**
 *
 * This class was generated by Fwmf Generated.
 * This class corresponds to the database table sys_t_school_r_grade
 *
 * @fwmf.generated 2018-08-18 22:31:52
 */
public class SchoolRGradeInfoGenerateBean {
    /**
     * Database Column Remarks:
     *   年级ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column sys_t_school_r_grade.GRADE_ID
     *
     * @fwmf.generated 2018-08-18 22:31:52
     */
    private Long gradeId;

    /**
     * Database Column Remarks:
     *   学校ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column sys_t_school_r_grade.SCHOOL_ID
     *
     * @fwmf.generated 2018-08-18 22:31:52
     */
    private Long schoolId;

    /**
     * Database Column Remarks:
     *   年级CODE
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column sys_t_school_r_grade.GRADE_CODE
     *
     * @fwmf.generated 2018-08-18 22:31:52
     */
    private String gradeCode;

    /**
     * Database Column Remarks:
     *   年级名称
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column sys_t_school_r_grade.GRADE_NAME
     *
     * @fwmf.generated 2018-08-18 22:31:52
     */
    private String gradeName;

    /**
     * Database Column Remarks:
     *   年级别名
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column sys_t_school_r_grade.GRADE_ALIAS
     *
     * @fwmf.generated 2018-08-18 22:31:52
     */
    private String gradeAlias;

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column sys_t_school_r_grade.GRADE_ID
     *
     * @return the value of sys_t_school_r_grade.GRADE_ID
     *
     * @fwmf.generated 2018-08-18 22:31:52
     */
    public Long getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column sys_t_school_r_grade.GRADE_ID
     *
     * @param gradeId the value for sys_t_school_r_grade.GRADE_ID
     *
     * @fwmf.generated 2018-08-18 22:31:52
     */
    public void setGradeId(Long gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column sys_t_school_r_grade.SCHOOL_ID
     *
     * @return the value of sys_t_school_r_grade.SCHOOL_ID
     *
     * @fwmf.generated 2018-08-18 22:31:52
     */
    public Long getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column sys_t_school_r_grade.SCHOOL_ID
     *
     * @param schoolId the value for sys_t_school_r_grade.SCHOOL_ID
     *
     * @fwmf.generated 2018-08-18 22:31:52
     */
    public void setSchoolId(Long schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column sys_t_school_r_grade.GRADE_CODE
     *
     * @return the value of sys_t_school_r_grade.GRADE_CODE
     *
     * @fwmf.generated 2018-08-18 22:31:52
     */
    public String getGradeCode() {
        return gradeCode;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column sys_t_school_r_grade.GRADE_CODE
     *
     * @param gradeCode the value for sys_t_school_r_grade.GRADE_CODE
     *
     * @fwmf.generated 2018-08-18 22:31:52
     */
    public void setGradeCode(String gradeCode) {
        this.gradeCode = gradeCode == null ? null : gradeCode.trim();
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column sys_t_school_r_grade.GRADE_NAME
     *
     * @return the value of sys_t_school_r_grade.GRADE_NAME
     *
     * @fwmf.generated 2018-08-18 22:31:52
     */
    public String getGradeName() {
        return gradeName;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column sys_t_school_r_grade.GRADE_NAME
     *
     * @param gradeName the value for sys_t_school_r_grade.GRADE_NAME
     *
     * @fwmf.generated 2018-08-18 22:31:52
     */
    public void setGradeName(String gradeName) {
        this.gradeName = gradeName == null ? null : gradeName.trim();
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column sys_t_school_r_grade.GRADE_ALIAS
     *
     * @return the value of sys_t_school_r_grade.GRADE_ALIAS
     *
     * @fwmf.generated 2018-08-18 22:31:52
     */
    public String getGradeAlias() {
        return gradeAlias;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column sys_t_school_r_grade.GRADE_ALIAS
     *
     * @param gradeAlias the value for sys_t_school_r_grade.GRADE_ALIAS
     *
     * @fwmf.generated 2018-08-18 22:31:52
     */
    public void setGradeAlias(String gradeAlias) {
        this.gradeAlias = gradeAlias == null ? null : gradeAlias.trim();
    }
}