/**
 * This file was generator by Fwmf Generated
 * ！！！Do not modify this file！！ 
 *
 * @fwmf.generated 2018-11-15 08:50:34
 */
package cn.faury.fwmf.module.service.category.generate.mapper;

import cn.faury.fwmf.module.api.category.bean.SystemRTagBean;
import cn.faury.fwmf.module.api.category.generate.bean.SystemRTagGenerateBean;
import cn.faury.fwmf.module.service.category.generate.sqlProvider.SystemRTagGenerateSqlProvider;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.ResultType;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SystemRTagGenerateMapper {
    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table product_t_tag_r_system
     *
     * @fwmf.generated 2018-11-15 08:50:34
     */
    @Delete({
        "delete from product_t_tag_r_system",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table product_t_tag_r_system
     *
     * @fwmf.generated 2018-11-15 08:50:34
     */
    @Insert({
        "insert into product_t_tag_r_system (ID, SYSTEM_ID, ",
        "TAG_ID, IS_LEAF)",
        "values (#{id,jdbcType=BIGINT}, #{systemId,jdbcType=BIGINT}, ",
        "#{tagId,jdbcType=BIGINT}, #{isLeaf,jdbcType=CHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(SystemRTagGenerateBean record);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table product_t_tag_r_system
     *
     * @fwmf.generated 2018-11-15 08:50:34
     */
    @InsertProvider(type=SystemRTagGenerateSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(SystemRTagGenerateBean record);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table product_t_tag_r_system
     *
     * @fwmf.generated 2018-11-15 08:50:34
     */
    @SelectProvider(type=SystemRTagGenerateSqlProvider.class, method="search")
    @ResultType(SystemRTagBean.class)
    List<SystemRTagBean> search(Map<String, Object> params);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table product_t_tag_r_system
     *
     * @fwmf.generated 2018-11-15 08:50:34
     */
    @Select({
        "select",
        "ID, SYSTEM_ID, TAG_ID, IS_LEAF",
        "from product_t_tag_r_system",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="SYSTEM_ID", property="systemId", jdbcType=JdbcType.BIGINT),
        @Result(column="TAG_ID", property="tagId", jdbcType=JdbcType.BIGINT),
        @Result(column="IS_LEAF", property="isLeaf", jdbcType=JdbcType.CHAR)
    })
    SystemRTagBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table product_t_tag_r_system
     *
     * @fwmf.generated 2018-11-15 08:50:34
     */
    @UpdateProvider(type=SystemRTagGenerateSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SystemRTagGenerateBean record);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table product_t_tag_r_system
     *
     * @fwmf.generated 2018-11-15 08:50:34
     */
    @Update({
        "update product_t_tag_r_system",
        "set SYSTEM_ID = #{systemId,jdbcType=BIGINT},",
          "TAG_ID = #{tagId,jdbcType=BIGINT},",
          "IS_LEAF = #{isLeaf,jdbcType=CHAR}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SystemRTagGenerateBean record);
}