package cn.faury.fwmf.module.service.order.generate.mapper;

import cn.faury.fwmf.module.api.order.bean.GoodsStockBean;
import cn.faury.fwmf.module.api.order.generate.bean.GoodsStockGenerateBean;
import cn.faury.fwmf.module.service.order.generate.sqlProvider.GoodsStockGenerateSqlProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface GoodsStockGenerateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_goods_stock_info
     *
     * @mbg.generated Sun Aug 05 23:04:46 CST 2018
     */
    @Delete({
        "delete from order_t_goods_stock_info",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_goods_stock_info
     *
     * @mbg.generated Sun Aug 05 23:04:46 CST 2018
     */
    @Insert({
        "insert into order_t_goods_stock_info (ID, GOODS_ID, ",
        "STOCK, DEMO, CREATE_PERSON, ",
        "CREATE_TIME, IS_DELETE)",
        "values (#{id,jdbcType=BIGINT}, #{goodsId,jdbcType=BIGINT}, ",
        "#{stock,jdbcType=INTEGER}, #{demo,jdbcType=VARCHAR}, #{createPerson,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{isDelete,jdbcType=CHAR})"
    })
    @Options(useGeneratedKeys = true)
    int insert(GoodsStockGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_goods_stock_info
     *
     * @mbg.generated Sun Aug 05 23:04:46 CST 2018
     */
    @InsertProvider(type=GoodsStockGenerateSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys = true)
    int insertSelective(GoodsStockGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_goods_stock_info
     *
     * @mbg.generated Sun Aug 05 23:04:46 CST 2018
     */
    @Select({
        "select",
        "ID, GOODS_ID, STOCK, DEMO, CREATE_PERSON, CREATE_TIME, IS_DELETE",
        "from order_t_goods_stock_info",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="GOODS_ID", property="goodsId", jdbcType=JdbcType.BIGINT),
        @Result(column="STOCK", property="stock", jdbcType=JdbcType.INTEGER),
        @Result(column="DEMO", property="demo", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_PERSON", property="createPerson", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="IS_DELETE", property="isDelete", jdbcType=JdbcType.CHAR)
    })
    GoodsStockBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_goods_stock_info
     *
     * @mbg.generated Sun Aug 05 23:04:46 CST 2018
     */
    @UpdateProvider(type=GoodsStockGenerateSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GoodsStockGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_goods_stock_info
     *
     * @mbg.generated Sun Aug 05 23:04:46 CST 2018
     */
    @Update({
        "update order_t_goods_stock_info",
        "set GOODS_ID = #{goodsId,jdbcType=BIGINT},",
          "STOCK = #{stock,jdbcType=INTEGER},",
          "DEMO = #{demo,jdbcType=VARCHAR},",
          "CREATE_PERSON = #{createPerson,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "IS_DELETE = #{isDelete,jdbcType=CHAR}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(GoodsStockGenerateBean record);
}