package cn.faury.fwmf.module.service.order.generate.mapper;

import cn.faury.fwmf.module.api.order.bean.OrderPayInfoBean;
import cn.faury.fwmf.module.api.order.generate.bean.OrderPayInfoGenerateBean;
import cn.faury.fwmf.module.service.order.generate.sqlProvider.OrderPayInfoGenerateSqlProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface OrderPayInfoGenerateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_pay_info
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    @Delete({
        "delete from order_t_order_pay_info",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_pay_info
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    @Insert({
        "insert into order_t_order_pay_info (ID, ORDER_ID, ",
        "PAY_AMOUNT, PAY_STATE, ",
        "PAY_TIME, PAY_STYLE, ",
        "CREATE_PERSON, CREATE_PERSON_NAME, ",
        "CREATE_TIME, UPDATE_PERSON, ",
        "UPDATE_PERSON_NAME, UPDATE_TIME, ",
        "DZ_STATE)",
        "values (#{id,jdbcType=BIGINT}, #{orderId,jdbcType=BIGINT}, ",
        "#{payAmount,jdbcType=DECIMAL}, #{payState,jdbcType=CHAR}, ",
        "#{payTime,jdbcType=TIMESTAMP}, #{payStyle,jdbcType=CHAR}, ",
        "#{createPerson,jdbcType=BIGINT}, #{createPersonName,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updatePerson,jdbcType=BIGINT}, ",
        "#{updatePersonName,jdbcType=VARCHAR}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{dzState,jdbcType=INTEGER})"
    })
    @Options(useGeneratedKeys = true)
    int insert(OrderPayInfoGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_pay_info
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    @InsertProvider(type=OrderPayInfoGenerateSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys = true)
    int insertSelective(OrderPayInfoGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_pay_info
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    @Select({
        "select",
        "ID, ORDER_ID, PAY_AMOUNT, PAY_STATE, PAY_TIME, PAY_STYLE, CREATE_PERSON, CREATE_PERSON_NAME, ",
        "CREATE_TIME, UPDATE_PERSON, UPDATE_PERSON_NAME, UPDATE_TIME, DZ_STATE",
        "from order_t_order_pay_info",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="ORDER_ID", property="orderId", jdbcType=JdbcType.BIGINT),
        @Result(column="PAY_AMOUNT", property="payAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAY_STATE", property="payState", jdbcType=JdbcType.CHAR),
        @Result(column="PAY_TIME", property="payTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PAY_STYLE", property="payStyle", jdbcType=JdbcType.CHAR),
        @Result(column="CREATE_PERSON", property="createPerson", jdbcType=JdbcType.BIGINT),
        @Result(column="CREATE_PERSON_NAME", property="createPersonName", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_PERSON", property="updatePerson", jdbcType=JdbcType.BIGINT),
        @Result(column="UPDATE_PERSON_NAME", property="updatePersonName", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DZ_STATE", property="dzState", jdbcType=JdbcType.INTEGER)
    })
    OrderPayInfoBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_pay_info
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    @UpdateProvider(type=OrderPayInfoGenerateSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OrderPayInfoGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_pay_info
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    @Update({
        "update order_t_order_pay_info",
        "set ORDER_ID = #{orderId,jdbcType=BIGINT},",
          "PAY_AMOUNT = #{payAmount,jdbcType=DECIMAL},",
          "PAY_STATE = #{payState,jdbcType=CHAR},",
          "PAY_TIME = #{payTime,jdbcType=TIMESTAMP},",
          "PAY_STYLE = #{payStyle,jdbcType=CHAR},",
          "CREATE_PERSON = #{createPerson,jdbcType=BIGINT},",
          "CREATE_PERSON_NAME = #{createPersonName,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_PERSON = #{updatePerson,jdbcType=BIGINT},",
          "UPDATE_PERSON_NAME = #{updatePersonName,jdbcType=VARCHAR},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP},",
          "DZ_STATE = #{dzState,jdbcType=INTEGER}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(OrderPayInfoGenerateBean record);
}