package cn.faury.fwmf.module.service.order.generate.mapper;

import cn.faury.fwmf.module.api.order.bean.OrderRLogisticsBean;
import cn.faury.fwmf.module.api.order.generate.bean.OrderRLogisticsGenerateBean;
import cn.faury.fwmf.module.service.order.generate.sqlProvider.OrderRLogisticsGenerateSqlProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface OrderRLogisticsGenerateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_r_logistics
     *
     * @mbg.generated Mon Aug 13 11:37:09 CST 2018
     */
    @Delete({
        "delete from order_t_order_r_logistics",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_r_logistics
     *
     * @mbg.generated Mon Aug 13 11:37:09 CST 2018
     */
    @Insert({
        "insert into order_t_order_r_logistics (ID, ORDER_ID, ",
        "INSERT_TIME, ACCEPT_TIME, ",
        "ACCEPT_STATION, STATE)",
        "values (#{id,jdbcType=BIGINT}, #{orderId,jdbcType=BIGINT}, ",
        "#{insertTime,jdbcType=TIMESTAMP}, #{acceptTime,jdbcType=VARCHAR}, ",
        "#{acceptStation,jdbcType=VARCHAR}, #{state,jdbcType=CHAR})"
    })
    @Options(useGeneratedKeys = true)
    int insert(OrderRLogisticsGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_r_logistics
     *
     * @mbg.generated Mon Aug 13 11:37:09 CST 2018
     */
    @InsertProvider(type=OrderRLogisticsGenerateSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys = true)
    int insertSelective(OrderRLogisticsGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_r_logistics
     *
     * @mbg.generated Mon Aug 13 11:37:09 CST 2018
     */
    @Select({
        "select",
        "ID, ORDER_ID, INSERT_TIME, ACCEPT_TIME, ACCEPT_STATION, STATE",
        "from order_t_order_r_logistics",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="ORDER_ID", property="orderId", jdbcType=JdbcType.BIGINT),
        @Result(column="INSERT_TIME", property="insertTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="ACCEPT_TIME", property="acceptTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACCEPT_STATION", property="acceptStation", jdbcType=JdbcType.VARCHAR),
        @Result(column="STATE", property="state", jdbcType=JdbcType.CHAR)
    })
    OrderRLogisticsBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_r_logistics
     *
     * @mbg.generated Mon Aug 13 11:37:09 CST 2018
     */
    @UpdateProvider(type=OrderRLogisticsGenerateSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OrderRLogisticsGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_r_logistics
     *
     * @mbg.generated Mon Aug 13 11:37:09 CST 2018
     */
    @Update({
        "update order_t_order_r_logistics",
        "set ORDER_ID = #{orderId,jdbcType=BIGINT},",
          "INSERT_TIME = #{insertTime,jdbcType=TIMESTAMP},",
          "ACCEPT_TIME = #{acceptTime,jdbcType=VARCHAR},",
          "ACCEPT_STATION = #{acceptStation,jdbcType=VARCHAR},",
          "STATE = #{state,jdbcType=CHAR}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(OrderRLogisticsGenerateBean record);
}