package cn.faury.fwmf.module.service.order.generate.mapper;

import cn.faury.fwmf.module.api.order.bean.OrderOperateInfoBean;
import cn.faury.fwmf.module.api.order.generate.bean.OrderOperateInfoGenerateBean;
import cn.faury.fwmf.module.service.order.generate.sqlProvider.OrderOperateInfoGenerateSqlProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface OrderOperateInfoGenerateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_operate_info
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    @Delete({
        "delete from order_t_order_operate_info",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_operate_info
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    @Insert({
        "insert into order_t_order_operate_info (ID, ORDER_ID, ",
        "OPERATE_TYPE_ID, OPERATE_TYPE_DESC, ",
        "OPERATER_ID, OPERATER_NAME, ",
        "IS_SHOPPING, OPERATE_CONTENT, ",
        "OPERATE_TIME)",
        "values (#{id,jdbcType=BIGINT}, #{orderId,jdbcType=BIGINT}, ",
        "#{operateTypeId,jdbcType=CHAR}, #{operateTypeDesc,jdbcType=VARCHAR}, ",
        "#{operaterId,jdbcType=BIGINT}, #{operaterName,jdbcType=VARCHAR}, ",
        "#{isShopping,jdbcType=CHAR}, #{operateContent,jdbcType=VARCHAR}, ",
        "#{operateTime,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys = true)
    int insert(OrderOperateInfoGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_operate_info
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    @InsertProvider(type=OrderOperateInfoGenerateSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys = true)
    int insertSelective(OrderOperateInfoGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_operate_info
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    @Select({
        "select",
        "ID, ORDER_ID, OPERATE_TYPE_ID, OPERATE_TYPE_DESC, OPERATER_ID, OPERATER_NAME, ",
        "IS_SHOPPING, OPERATE_CONTENT, OPERATE_TIME",
        "from order_t_order_operate_info",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="ORDER_ID", property="orderId", jdbcType=JdbcType.BIGINT),
        @Result(column="OPERATE_TYPE_ID", property="operateTypeId", jdbcType=JdbcType.CHAR),
        @Result(column="OPERATE_TYPE_DESC", property="operateTypeDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPERATER_ID", property="operaterId", jdbcType=JdbcType.BIGINT),
        @Result(column="OPERATER_NAME", property="operaterName", jdbcType=JdbcType.VARCHAR),
        @Result(column="IS_SHOPPING", property="isShopping", jdbcType=JdbcType.CHAR),
        @Result(column="OPERATE_CONTENT", property="operateContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPERATE_TIME", property="operateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    OrderOperateInfoBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_operate_info
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    @UpdateProvider(type=OrderOperateInfoGenerateSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OrderOperateInfoGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_operate_info
     *
     * @mbg.generated Mon Aug 06 14:43:55 CST 2018
     */
    @Update({
        "update order_t_order_operate_info",
        "set ORDER_ID = #{orderId,jdbcType=BIGINT},",
          "OPERATE_TYPE_ID = #{operateTypeId,jdbcType=CHAR},",
          "OPERATE_TYPE_DESC = #{operateTypeDesc,jdbcType=VARCHAR},",
          "OPERATER_ID = #{operaterId,jdbcType=BIGINT},",
          "OPERATER_NAME = #{operaterName,jdbcType=VARCHAR},",
          "IS_SHOPPING = #{isShopping,jdbcType=CHAR},",
          "OPERATE_CONTENT = #{operateContent,jdbcType=VARCHAR},",
          "OPERATE_TIME = #{operateTime,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(OrderOperateInfoGenerateBean record);
}