package cn.faury.fwmf.module.service.order.generate.mapper;

import cn.faury.fwmf.module.api.order.bean.PackageInfoBean;
import cn.faury.fwmf.module.api.order.generate.bean.PackageInfoGenerateBean;
import cn.faury.fwmf.module.service.order.generate.sqlProvider.PackageInfoGenerateSqlProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface PackageInfoGenerateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_package_info
     *
     * @mbg.generated Tue Aug 07 16:54:55 CST 2018
     */
    @Delete({
        "delete from order_t_package_info",
        "where PACKAGE_ID = #{packageId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long packageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_package_info
     *
     * @mbg.generated Tue Aug 07 16:54:55 CST 2018
     */
    @Insert({
        "insert into order_t_package_info (PACKAGE_ID, PACKAGE_NAME, ",
        "PACKAGE_PRICE, SHOP_ID, ",
        "STORE_ID, POSTAGE_ID, ",
        "IS_DELETE, CREATE_PERSON, ",
        "CREATE_PERSON_NAME, CREATE_TIME, ",
        "UPDATE_PERSON, UPDATE_PERSON_NAME, ",
        "UPDATE_TIME)",
        "values (#{packageId,jdbcType=BIGINT}, #{packageName,jdbcType=VARCHAR}, ",
        "#{packagePrice,jdbcType=DECIMAL}, #{shopId,jdbcType=BIGINT}, ",
        "#{storeId,jdbcType=BIGINT}, #{postageId,jdbcType=BIGINT}, ",
        "#{isDelete,jdbcType=CHAR}, #{createPerson,jdbcType=BIGINT}, ",
        "#{createPersonName,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updatePerson,jdbcType=BIGINT}, #{updatePersonName,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys = true,keyProperty = "packageId")
    int insert(PackageInfoGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_package_info
     *
     * @mbg.generated Tue Aug 07 16:54:55 CST 2018
     */
    @InsertProvider(type=PackageInfoGenerateSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys = true,keyProperty = "packageId")
    int insertSelective(PackageInfoGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_package_info
     *
     * @mbg.generated Tue Aug 07 16:54:55 CST 2018
     */
    @Select({
        "select",
        "PACKAGE_ID, PACKAGE_NAME, PACKAGE_PRICE, SHOP_ID, STORE_ID, POSTAGE_ID, IS_DELETE, ",
        "CREATE_PERSON, CREATE_PERSON_NAME, CREATE_TIME, UPDATE_PERSON, UPDATE_PERSON_NAME, ",
        "UPDATE_TIME",
        "from order_t_package_info",
        "where PACKAGE_ID = #{packageId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="PACKAGE_ID", property="packageId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="PACKAGE_NAME", property="packageName", jdbcType=JdbcType.VARCHAR),
        @Result(column="PACKAGE_PRICE", property="packagePrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="SHOP_ID", property="shopId", jdbcType=JdbcType.BIGINT),
        @Result(column="STORE_ID", property="storeId", jdbcType=JdbcType.BIGINT),
        @Result(column="POSTAGE_ID", property="postageId", jdbcType=JdbcType.BIGINT),
        @Result(column="IS_DELETE", property="isDelete", jdbcType=JdbcType.CHAR),
        @Result(column="CREATE_PERSON", property="createPerson", jdbcType=JdbcType.BIGINT),
        @Result(column="CREATE_PERSON_NAME", property="createPersonName", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_PERSON", property="updatePerson", jdbcType=JdbcType.BIGINT),
        @Result(column="UPDATE_PERSON_NAME", property="updatePersonName", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    PackageInfoBean selectByPrimaryKey(Long packageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_package_info
     *
     * @mbg.generated Tue Aug 07 16:54:55 CST 2018
     */
    @UpdateProvider(type=PackageInfoGenerateSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PackageInfoGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_package_info
     *
     * @mbg.generated Tue Aug 07 16:54:55 CST 2018
     */
    @Update({
        "update order_t_package_info",
        "set PACKAGE_NAME = #{packageName,jdbcType=VARCHAR},",
          "PACKAGE_PRICE = #{packagePrice,jdbcType=DECIMAL},",
          "SHOP_ID = #{shopId,jdbcType=BIGINT},",
          "STORE_ID = #{storeId,jdbcType=BIGINT},",
          "POSTAGE_ID = #{postageId,jdbcType=BIGINT},",
          "IS_DELETE = #{isDelete,jdbcType=CHAR},",
          "CREATE_PERSON = #{createPerson,jdbcType=BIGINT},",
          "CREATE_PERSON_NAME = #{createPersonName,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_PERSON = #{updatePerson,jdbcType=BIGINT},",
          "UPDATE_PERSON_NAME = #{updatePersonName,jdbcType=VARCHAR},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where PACKAGE_ID = #{packageId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(PackageInfoGenerateBean record);
}