package cn.faury.fwmf.module.service.order.generate.mapper;

import cn.faury.fwmf.module.api.order.bean.PromotionInfoBean;
import cn.faury.fwmf.module.api.order.generate.bean.PromotionInfoGenerateBean;
import cn.faury.fwmf.module.service.order.generate.sqlProvider.PromotionInfoGenerateSqlProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface PromotionInfoGenerateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_promotion_info
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    @Delete({
        "delete from order_t_promotion_info",
        "where PROMOTION_ID = #{promotionId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long promotionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_promotion_info
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    @Insert({
        "insert into order_t_promotion_info (PROMOTION_ID, PROMOTION_NAME, ",
        "PROMOTION_SUBJECT, PROMOTION_CONDITION, ",
        "CONDITION_VALUE, MEET_OPERATION, ",
        "MEET_VALUE, PROMOTION_START_TIME, ",
        "PROMOTION_END_TIME, CREATE_PERSON, ",
        "CREATE_TIME, UPDATE_PERSON, ",
        "UPDATE_TIME)",
        "values (#{promotionId,jdbcType=BIGINT}, #{promotionName,jdbcType=VARCHAR}, ",
        "#{promotionSubject,jdbcType=CHAR}, #{promotionCondition,jdbcType=CHAR}, ",
        "#{conditionValue,jdbcType=DECIMAL}, #{meetOperation,jdbcType=VARCHAR}, ",
        "#{meetValue,jdbcType=DECIMAL}, #{promotionStartTime,jdbcType=TIMESTAMP}, ",
        "#{promotionEndTime,jdbcType=TIMESTAMP}, #{createPerson,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updatePerson,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys = true,keyProperty = "promotionId")
    int insert(PromotionInfoGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_promotion_info
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    @InsertProvider(type=PromotionInfoGenerateSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys = true,keyProperty = "promotionId")
    int insertSelective(PromotionInfoGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_promotion_info
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    @Select({
        "select",
        "PROMOTION_ID, PROMOTION_NAME, PROMOTION_SUBJECT, PROMOTION_CONDITION, CONDITION_VALUE, ",
        "MEET_OPERATION, MEET_VALUE, PROMOTION_START_TIME, PROMOTION_END_TIME, CREATE_PERSON, ",
        "CREATE_TIME, UPDATE_PERSON, UPDATE_TIME",
        "from order_t_promotion_info",
        "where PROMOTION_ID = #{promotionId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="PROMOTION_ID", property="promotionId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="PROMOTION_NAME", property="promotionName", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROMOTION_SUBJECT", property="promotionSubject", jdbcType=JdbcType.CHAR),
        @Result(column="PROMOTION_CONDITION", property="promotionCondition", jdbcType=JdbcType.CHAR),
        @Result(column="CONDITION_VALUE", property="conditionValue", jdbcType=JdbcType.DECIMAL),
        @Result(column="MEET_OPERATION", property="meetOperation", jdbcType=JdbcType.VARCHAR),
        @Result(column="MEET_VALUE", property="meetValue", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROMOTION_START_TIME", property="promotionStartTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PROMOTION_END_TIME", property="promotionEndTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_PERSON", property="createPerson", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_PERSON", property="updatePerson", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    PromotionInfoBean selectByPrimaryKey(Long promotionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_promotion_info
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    @UpdateProvider(type=PromotionInfoGenerateSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PromotionInfoGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_promotion_info
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    @Update({
        "update order_t_promotion_info",
        "set PROMOTION_NAME = #{promotionName,jdbcType=VARCHAR},",
          "PROMOTION_SUBJECT = #{promotionSubject,jdbcType=CHAR},",
          "PROMOTION_CONDITION = #{promotionCondition,jdbcType=CHAR},",
          "CONDITION_VALUE = #{conditionValue,jdbcType=DECIMAL},",
          "MEET_OPERATION = #{meetOperation,jdbcType=VARCHAR},",
          "MEET_VALUE = #{meetValue,jdbcType=DECIMAL},",
          "PROMOTION_START_TIME = #{promotionStartTime,jdbcType=TIMESTAMP},",
          "PROMOTION_END_TIME = #{promotionEndTime,jdbcType=TIMESTAMP},",
          "CREATE_PERSON = #{createPerson,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_PERSON = #{updatePerson,jdbcType=VARCHAR},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where PROMOTION_ID = #{promotionId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(PromotionInfoGenerateBean record);
}