/**
 * This file was generator by Fwmf Generated
 * ！！！Do not modify this file！！ 
 *
 * @fwmf.generated 2018-12-08 15:12:42
 */
package cn.faury.fwmf.module.service.order.generate.mapper;

import cn.faury.fwmf.module.api.order.bean.WeixinCallbackRecordsBean;
import cn.faury.fwmf.module.api.order.generate.bean.WeixinCallbackRecordsGenerateBean;
import cn.faury.fwmf.module.service.order.generate.sqlProvider.WeixinCallbackRecordsGenerateSqlProvider;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.ResultType;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WeixinCallbackRecordsGenerateMapper {
    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table payment_t_weixin_callback_records
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    @Delete({
        "delete from payment_t_weixin_callback_records",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table payment_t_weixin_callback_records
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    @Insert({
        "insert into payment_t_weixin_callback_records (ID, OUT_TRADE_NO, ",
        "TRANSACTION_ID, RESULT_CODE, ",
        "PARAMETER_LIST, CALLBACK_TIME)",
        "values (#{id,jdbcType=BIGINT}, #{outTradeNo,jdbcType=VARCHAR}, ",
        "#{transactionId,jdbcType=VARCHAR}, #{resultCode,jdbcType=VARCHAR}, ",
        "#{parameterList,jdbcType=VARCHAR}, #{callbackTime,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(WeixinCallbackRecordsGenerateBean record);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table payment_t_weixin_callback_records
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    @InsertProvider(type=WeixinCallbackRecordsGenerateSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(WeixinCallbackRecordsGenerateBean record);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table payment_t_weixin_callback_records
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    @SelectProvider(type=WeixinCallbackRecordsGenerateSqlProvider.class, method="search")
    @ResultType(WeixinCallbackRecordsBean.class)
    List<WeixinCallbackRecordsBean> search(Map<String, Object> params);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table payment_t_weixin_callback_records
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    @Select({
        "select",
        "ID, OUT_TRADE_NO, TRANSACTION_ID, RESULT_CODE, PARAMETER_LIST, CALLBACK_TIME",
        "from payment_t_weixin_callback_records",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="OUT_TRADE_NO", property="outTradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANSACTION_ID", property="transactionId", jdbcType=JdbcType.VARCHAR),
        @Result(column="RESULT_CODE", property="resultCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="PARAMETER_LIST", property="parameterList", jdbcType=JdbcType.VARCHAR),
        @Result(column="CALLBACK_TIME", property="callbackTime", jdbcType=JdbcType.TIMESTAMP)
    })
    WeixinCallbackRecordsBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table payment_t_weixin_callback_records
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    @UpdateProvider(type=WeixinCallbackRecordsGenerateSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WeixinCallbackRecordsGenerateBean record);

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table payment_t_weixin_callback_records
     *
     * @fwmf.generated 2018-12-08 15:12:42
     */
    @Update({
        "update payment_t_weixin_callback_records",
        "set OUT_TRADE_NO = #{outTradeNo,jdbcType=VARCHAR},",
          "TRANSACTION_ID = #{transactionId,jdbcType=VARCHAR},",
          "RESULT_CODE = #{resultCode,jdbcType=VARCHAR},",
          "PARAMETER_LIST = #{parameterList,jdbcType=VARCHAR},",
          "CALLBACK_TIME = #{callbackTime,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(WeixinCallbackRecordsGenerateBean record);
}