/**
 * This file was generator by Fwmf Generated
 * ！！！Do not modify this file！！ 
 *
 * @fwmf.generated 2018-11-10 14:29:03
 */
package cn.faury.fwmf.module.service.school.generate.sqlProvider;

import cn.faury.fwmf.module.api.school.generate.bean.SchoolRGradeRClassInfoGenerateBean;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class SchoolRGradeRClassInfoGenerateSqlProvider {

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table sys_t_school_r_grade_r_class
     *
     * @fwmf.generated 2018-11-10 14:29:03
     */
    public String insertSelective(SchoolRGradeRClassInfoGenerateBean record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("sys_t_school_r_grade_r_class");
        
        if (record.getClassId() != null) {
            sql.VALUES("CLASS_ID", "#{classId,jdbcType=BIGINT}");
        }
        
        if (record.getGradeId() != null) {
            sql.VALUES("GRADE_ID", "#{gradeId,jdbcType=BIGINT}");
        }
        
        if (record.getSchoolId() != null) {
            sql.VALUES("SCHOOL_ID", "#{schoolId,jdbcType=BIGINT}");
        }
        
        if (record.getClassCode() != null) {
            sql.VALUES("CLASS_CODE", "#{classCode,jdbcType=VARCHAR}");
        }
        
        if (record.getClassName() != null) {
            sql.VALUES("CLASS_NAME", "#{className,jdbcType=VARCHAR}");
        }
        
        if (record.getClassAlias() != null) {
            sql.VALUES("CLASS_ALIAS", "#{classAlias,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table sys_t_school_r_grade_r_class
     *
     * @fwmf.generated 2018-11-10 14:29:03
     */
    public String updateByPrimaryKeySelective(SchoolRGradeRClassInfoGenerateBean record) {
        SQL sql = new SQL();
        sql.UPDATE("sys_t_school_r_grade_r_class");
        
        if (record.getGradeId() != null) {
            sql.SET("GRADE_ID = #{gradeId,jdbcType=BIGINT}");
        }
        
        if (record.getSchoolId() != null) {
            sql.SET("SCHOOL_ID = #{schoolId,jdbcType=BIGINT}");
        }
        
        if (record.getClassCode() != null) {
            sql.SET("CLASS_CODE = #{classCode,jdbcType=VARCHAR}");
        }
        
        if (record.getClassName() != null) {
            sql.SET("CLASS_NAME = #{className,jdbcType=VARCHAR}");
        }
        
        if (record.getClassAlias() != null) {
            sql.SET("CLASS_ALIAS = #{classAlias,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("CLASS_ID = #{classId,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method corresponds to the database table sys_t_school_r_grade_r_class
     *
     * @fwmf.generated 2018-11-10 14:29:03
     */
    public String search(Map<String, Object> params) {
        SQL sql = new SQL();
        sql.SELECT("CLASS_ID, GRADE_ID, SCHOOL_ID, CLASS_CODE, CLASS_NAME, CLASS_ALIAS");
        
        sql.FROM("sys_t_school_r_grade_r_class");
        
        if (params.get("classId")!=null){
            sql.WHERE("CLASS_ID=#{classId,jdbcType=BIGINT}");
        }
        if (params.get("gradeId")!=null){
            sql.WHERE("GRADE_ID=#{gradeId,jdbcType=BIGINT}");
        }
        if (params.get("schoolId")!=null){
            sql.WHERE("SCHOOL_ID=#{schoolId,jdbcType=BIGINT}");
        }
        if (params.get("classCode")!=null){
            sql.WHERE("CLASS_CODE=#{classCode,jdbcType=VARCHAR}");
        }
        if (params.get("classCodeLike")!=null){
            sql.WHERE("CLASS_CODE LIKE CONCAT('%',#{classCodeLike,jdbcType=VARCHAR},'%')");
        }
        if (params.get("className")!=null){
            sql.WHERE("CLASS_NAME=#{className,jdbcType=VARCHAR}");
        }
        if (params.get("classNameLike")!=null){
            sql.WHERE("CLASS_NAME LIKE CONCAT('%',#{classNameLike,jdbcType=VARCHAR},'%')");
        }
        if (params.get("classAlias")!=null){
            sql.WHERE("CLASS_ALIAS=#{classAlias,jdbcType=VARCHAR}");
        }
        if (params.get("classAliasLike")!=null){
            sql.WHERE("CLASS_ALIAS LIKE CONCAT('%',#{classAliasLike,jdbcType=VARCHAR},'%')");
        }
        if (params.get("ORDER_BY") != null){
            String orderBy = (String) params.get("ORDER_BY");
            String[] columns = orderBy.split(",");
            for (int i = 0; i < columns.length; i = i + 2) {
                if (i+1<columns.length){
                    sql.ORDER_BY(String.format("%s %s",columns[i],columns[i+1]));
                } else {
                    sql.ORDER_BY(columns[i]);
                }
            }
        }
        
        return sql.toString();
    }
}