/**
 * This file was generator by Fwmf Generated
 * ！！！Do not modify this file！！ 
 *
 * @fwmf.generated 2018-09-19 14:14:56
 */
package cn.faury.fwmf.module.api.code.generate.bean;

/**
 * Database Table Remarks:
 *   数据字典表
 *
 * This class was generated by Fwmf Generated.
 * This class corresponds to the database table sys_t_code_info
 *
 * @fwmf.generated 2018-09-19 14:14:56
 */
public class CodeInfoGenerateBean {
    /**
     * Database Column Remarks:
     *   字典ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column sys_t_code_info.CODE_ID
     *
     * @fwmf.generated 2018-09-19 14:14:56
     */
    private Long codeId;

    /**
     * Database Column Remarks:
     *   字典分组ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column sys_t_code_info.CODE_GROUP_ID
     *
     * @fwmf.generated 2018-09-19 14:14:56
     */
    private Long codeGroupId;

    /**
     * Database Column Remarks:
     *   字典名称
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column sys_t_code_info.CODE_NAME
     *
     * @fwmf.generated 2018-09-19 14:14:56
     */
    private String codeName;

    /**
     * Database Column Remarks:
     *   字典编码
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column sys_t_code_info.CODE_CODE
     *
     * @fwmf.generated 2018-09-19 14:14:56
     */
    private String codeCode;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column sys_t_code_info.CODE_ORDER
     *
     * @fwmf.generated 2018-09-19 14:14:56
     */
    private Integer codeOrder;

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column sys_t_code_info.CODE_ID
     *
     * @return the value of sys_t_code_info.CODE_ID
     *
     * @fwmf.generated 2018-09-19 14:14:56
     */
    public Long getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column sys_t_code_info.CODE_ID
     *
     * @param codeId the value for sys_t_code_info.CODE_ID
     *
     * @fwmf.generated 2018-09-19 14:14:56
     */
    public void setCodeId(Long codeId) {
        this.codeId = codeId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column sys_t_code_info.CODE_GROUP_ID
     *
     * @return the value of sys_t_code_info.CODE_GROUP_ID
     *
     * @fwmf.generated 2018-09-19 14:14:56
     */
    public Long getCodeGroupId() {
        return codeGroupId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column sys_t_code_info.CODE_GROUP_ID
     *
     * @param codeGroupId the value for sys_t_code_info.CODE_GROUP_ID
     *
     * @fwmf.generated 2018-09-19 14:14:56
     */
    public void setCodeGroupId(Long codeGroupId) {
        this.codeGroupId = codeGroupId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column sys_t_code_info.CODE_NAME
     *
     * @return the value of sys_t_code_info.CODE_NAME
     *
     * @fwmf.generated 2018-09-19 14:14:56
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column sys_t_code_info.CODE_NAME
     *
     * @param codeName the value for sys_t_code_info.CODE_NAME
     *
     * @fwmf.generated 2018-09-19 14:14:56
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName == null ? null : codeName.trim();
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column sys_t_code_info.CODE_CODE
     *
     * @return the value of sys_t_code_info.CODE_CODE
     *
     * @fwmf.generated 2018-09-19 14:14:56
     */
    public String getCodeCode() {
        return codeCode;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column sys_t_code_info.CODE_CODE
     *
     * @param codeCode the value for sys_t_code_info.CODE_CODE
     *
     * @fwmf.generated 2018-09-19 14:14:56
     */
    public void setCodeCode(String codeCode) {
        this.codeCode = codeCode == null ? null : codeCode.trim();
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column sys_t_code_info.CODE_ORDER
     *
     * @return the value of sys_t_code_info.CODE_ORDER
     *
     * @fwmf.generated 2018-09-19 14:14:56
     */
    public Integer getCodeOrder() {
        return codeOrder;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column sys_t_code_info.CODE_ORDER
     *
     * @param codeOrder the value for sys_t_code_info.CODE_ORDER
     *
     * @fwmf.generated 2018-09-19 14:14:56
     */
    public void setCodeOrder(Integer codeOrder) {
        this.codeOrder = codeOrder;
    }
}