package cn.faury.fwmf.module.service.payment.generate.mapper;

import cn.faury.fwmf.module.api.payment.generate.bean.WeixinCallbackRecordsGenerateBean;
import cn.faury.fwmf.module.service.payment.generate.sqlProvider.WeixinCallbackRecordsGenerateSqlProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface WeixinCallbackRecordsGenerateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_t_weixin_callback_records
     *
     * @mbg.generated Tue Aug 07 09:22:28 CST 2018
     */
    @Delete({
        "delete from payment_t_weixin_callback_records",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_t_weixin_callback_records
     *
     * @mbg.generated Tue Aug 07 09:22:28 CST 2018
     */
    @Insert({
        "insert into payment_t_weixin_callback_records (ID, OUT_TRADE_NO, ",
        "TRANSACTION_ID, RESULT_CODE, ",
        "PARAMETER_LIST, CALLBACK_TIME)",
        "values (#{id,jdbcType=BIGINT}, #{outTradeNo,jdbcType=VARCHAR}, ",
        "#{transactionId,jdbcType=VARCHAR}, #{resultCode,jdbcType=VARCHAR}, ",
        "#{parameterList,jdbcType=VARCHAR}, #{callbackTime,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys = true)
    int insert(WeixinCallbackRecordsGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_t_weixin_callback_records
     *
     * @mbg.generated Tue Aug 07 09:22:28 CST 2018
     */
    @InsertProvider(type=WeixinCallbackRecordsGenerateSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys = true)
    int insertSelective(WeixinCallbackRecordsGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_t_weixin_callback_records
     *
     * @mbg.generated Tue Aug 07 09:22:28 CST 2018
     */
    @Select({
        "select",
        "ID, OUT_TRADE_NO, TRANSACTION_ID, RESULT_CODE, PARAMETER_LIST, CALLBACK_TIME",
        "from payment_t_weixin_callback_records",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="OUT_TRADE_NO", property="outTradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANSACTION_ID", property="transactionId", jdbcType=JdbcType.VARCHAR),
        @Result(column="RESULT_CODE", property="resultCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="PARAMETER_LIST", property="parameterList", jdbcType=JdbcType.VARCHAR),
        @Result(column="CALLBACK_TIME", property="callbackTime", jdbcType=JdbcType.TIMESTAMP)
    })
    WeixinCallbackRecordsGenerateBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_t_weixin_callback_records
     *
     * @mbg.generated Tue Aug 07 09:22:28 CST 2018
     */
    @UpdateProvider(type=WeixinCallbackRecordsGenerateSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WeixinCallbackRecordsGenerateBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_t_weixin_callback_records
     *
     * @mbg.generated Tue Aug 07 09:22:28 CST 2018
     */
    @Update({
        "update payment_t_weixin_callback_records",
        "set OUT_TRADE_NO = #{outTradeNo,jdbcType=VARCHAR},",
          "TRANSACTION_ID = #{transactionId,jdbcType=VARCHAR},",
          "RESULT_CODE = #{resultCode,jdbcType=VARCHAR},",
          "PARAMETER_LIST = #{parameterList,jdbcType=VARCHAR},",
          "CALLBACK_TIME = #{callbackTime,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(WeixinCallbackRecordsGenerateBean record);
}