/**
 * This file was generator by Fwmf Generated
 * ！！！Do not modify this file！！ 
 *
 * @fwmf.generated 2018-12-14 09:33:56
 */
package cn.faury.fwmf.module.api.menu.generate.bean;

/**
 * Database Table Remarks:
 *   角色关联功能按钮表
 *
 * This class was generated by Fwmf Generated.
 * This class corresponds to the database table sys_t_role_r_function
 *
 * @fwmf.generated 2018-12-14 09:33:56
 */
public class RoleRFunctionGenerateBean {
    /**
     * Database Column Remarks:
     *   唯一主键
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column sys_t_role_r_function.ID
     *
     * @fwmf.generated 2018-12-14 09:33:56
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   角色ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column sys_t_role_r_function.ROLE_ID
     *
     * @fwmf.generated 2018-12-14 09:33:56
     */
    private Long roleId;

    /**
     * Database Column Remarks:
     *   功能按钮ID
     *
     * This field was generated by Fwmf Generated.
     * This field corresponds to the database column sys_t_role_r_function.FUNCTION_ID
     *
     * @fwmf.generated 2018-12-14 09:33:56
     */
    private Long functionId;

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column sys_t_role_r_function.ID
     *
     * @return the value of sys_t_role_r_function.ID
     *
     * @fwmf.generated 2018-12-14 09:33:56
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column sys_t_role_r_function.ID
     *
     * @param id the value for sys_t_role_r_function.ID
     *
     * @fwmf.generated 2018-12-14 09:33:56
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column sys_t_role_r_function.ROLE_ID
     *
     * @return the value of sys_t_role_r_function.ROLE_ID
     *
     * @fwmf.generated 2018-12-14 09:33:56
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column sys_t_role_r_function.ROLE_ID
     *
     * @param roleId the value for sys_t_role_r_function.ROLE_ID
     *
     * @fwmf.generated 2018-12-14 09:33:56
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method returns the value of the database column sys_t_role_r_function.FUNCTION_ID
     *
     * @return the value of sys_t_role_r_function.FUNCTION_ID
     *
     * @fwmf.generated 2018-12-14 09:33:56
     */
    public Long getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by Fwmf Generated.
     * This method sets the value of the database column sys_t_role_r_function.FUNCTION_ID
     *
     * @param functionId the value for sys_t_role_r_function.FUNCTION_ID
     *
     * @fwmf.generated 2018-12-14 09:33:56
     */
    public void setFunctionId(Long functionId) {
        this.functionId = functionId;
    }
}