package cn.faury.fwmf.module.service.school.mapper;

import cn.faury.fdk.mybatis.AutoScannedMapper;
import cn.faury.fwmf.module.api.school.bean.SchoolRGradeInfoBean;
import cn.faury.fwmf.module.service.school.sqlProvider.SchoolRGradeInfoSqlProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;
import java.util.Map;

@AutoScannedMapper
public interface SchoolRGradeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_t_school_r_grade
     *
     * @mbg.generated Tue Jul 31 10:54:33 CST 2018
     */
    @Delete({
            "delete from sys_t_school_r_grade",
            "where GRADE_ID = #{gradeId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long gradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_t_school_r_grade
     *
     * @mbg.generated Tue Jul 31 10:54:33 CST 2018
     */
    @Insert({
            "insert into sys_t_school_r_grade (GRADE_ID, SCHOOL_ID, ",
            "GRADE_CODE, GRADE_NAME, ",
            "GRADE_ALIAS)",
            "values (#{gradeId,jdbcType=BIGINT}, #{schoolId,jdbcType=BIGINT}, ",
            "#{gradeCode,jdbcType=VARCHAR}, #{gradeName,jdbcType=VARCHAR}, ",
            "#{gradeAlias,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys = true,keyProperty = "gradeId")
    int insert(SchoolRGradeInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_t_school_r_grade
     *
     * @mbg.generated Tue Jul 31 10:54:33 CST 2018
     */
    @InsertProvider(type = SchoolRGradeInfoSqlProvider.class, method = "insertSelective")
    @Options(useGeneratedKeys = true,keyProperty = "gradeId")
    int insertSelective(SchoolRGradeInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_t_school_r_grade
     *
     * @mbg.generated Tue Jul 31 10:54:33 CST 2018
     */
    @Select({
            "select",
            "GRADE_ID, SCHOOL_ID, GRADE_CODE, GRADE_NAME, GRADE_ALIAS",
            "from sys_t_school_r_grade",
            "where GRADE_ID = #{gradeId,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column = "GRADE_ID", property = "gradeId", jdbcType = JdbcType.BIGINT, id = true),
            @Result(column = "SCHOOL_ID", property = "schoolId", jdbcType = JdbcType.BIGINT),
            @Result(column = "GRADE_CODE", property = "gradeCode", jdbcType = JdbcType.VARCHAR),
            @Result(column = "GRADE_NAME", property = "gradeName", jdbcType = JdbcType.VARCHAR),
            @Result(column = "GRADE_ALIAS", property = "gradeAlias", jdbcType = JdbcType.VARCHAR)
    })
    SchoolRGradeInfoBean selectByPrimaryKey(Long gradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_t_school_r_grade
     *
     * @mbg.generated Tue Jul 31 10:54:33 CST 2018
     */
    @UpdateProvider(type = SchoolRGradeInfoSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SchoolRGradeInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_t_school_r_grade
     *
     * @mbg.generated Tue Jul 31 10:54:33 CST 2018
     */
    @Update({
            "update sys_t_school_r_grade",
            "set SCHOOL_ID = #{schoolId,jdbcType=BIGINT},",
            "GRADE_CODE = #{gradeCode,jdbcType=VARCHAR},",
            "GRADE_NAME = #{gradeName,jdbcType=VARCHAR},",
            "GRADE_ALIAS = #{gradeAlias,jdbcType=VARCHAR}",
            "where GRADE_ID = #{gradeId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SchoolRGradeInfoBean record);

    @SelectProvider(type = SchoolRGradeInfoSqlProvider.class, method = "search")
    @ResultType(SchoolRGradeInfoBean.class)
    List<SchoolRGradeInfoBean> search(Map<String, Object> params);
}