package cn.faury.fwmf.module.service.order.generate.sqlProvider;

import cn.faury.fwmf.module.api.order.generate.bean.GoodsStockGenerateBean;
import org.apache.ibatis.jdbc.SQL;

public class GoodsStockGenerateSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_goods_stock_info
     *
     * @mbg.generated Sun Aug 05 23:04:46 CST 2018
     */
    public String insertSelective(GoodsStockGenerateBean record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("order_t_goods_stock_info");
        
        if (record.getId() != null) {
            sql.VALUES("ID", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getGoodsId() != null) {
            sql.VALUES("GOODS_ID", "#{goodsId,jdbcType=BIGINT}");
        }
        
        if (record.getStock() != null) {
            sql.VALUES("STOCK", "#{stock,jdbcType=INTEGER}");
        }
        
        if (record.getDemo() != null) {
            sql.VALUES("DEMO", "#{demo,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatePerson() != null) {
            sql.VALUES("CREATE_PERSON", "#{createPerson,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("CREATE_TIME", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIsDelete() != null) {
            sql.VALUES("IS_DELETE", "#{isDelete,jdbcType=CHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_goods_stock_info
     *
     * @mbg.generated Sun Aug 05 23:04:46 CST 2018
     */
    public String updateByPrimaryKeySelective(GoodsStockGenerateBean record) {
        SQL sql = new SQL();
        sql.UPDATE("order_t_goods_stock_info");
        
        if (record.getGoodsId() != null) {
            sql.SET("GOODS_ID = #{goodsId,jdbcType=BIGINT}");
        }
        
        if (record.getStock() != null) {
            sql.SET("STOCK = #{stock,jdbcType=INTEGER}");
        }
        
        if (record.getDemo() != null) {
            sql.SET("DEMO = #{demo,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatePerson() != null) {
            sql.SET("CREATE_PERSON = #{createPerson,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("CREATE_TIME = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIsDelete() != null) {
            sql.SET("IS_DELETE = #{isDelete,jdbcType=CHAR}");
        }
        
        sql.WHERE("ID = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}