package cn.faury.fwmf.module.service.order.generate.sqlProvider;

import cn.faury.fwmf.module.api.order.generate.bean.OrderInfoGenerateBean;
import org.apache.ibatis.jdbc.SQL;

public class OrderInfoGenerateSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_info
     *
     * @mbg.generated Mon Aug 13 09:47:15 CST 2018
     */
    public String insertSelective(OrderInfoGenerateBean record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("order_t_order_info");
        
        sql.VALUES("ORDER_ID", "#{orderId,jdbcType=BIGINT}");
        
        if (record.getOrderCode() != null) {
            sql.VALUES("ORDER_CODE", "#{orderCode,jdbcType=CHAR}");
        }
        
        if (record.getBuyerId() != null) {
            sql.VALUES("BUYER_ID", "#{buyerId,jdbcType=BIGINT}");
        }
        
        if (record.getBuyerLogin() != null) {
            sql.VALUES("BUYER_LOGIN", "#{buyerLogin,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderState() != null) {
            sql.VALUES("ORDER_STATE", "#{orderState,jdbcType=CHAR}");
        }
        
        if (record.getGoodsCount() != null) {
            sql.VALUES("GOODS_COUNT", "#{goodsCount,jdbcType=INTEGER}");
        }
        
        if (record.getGoodsPrice() != null) {
            sql.VALUES("GOODS_PRICE", "#{goodsPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getPostPrice() != null) {
            sql.VALUES("POST_PRICE", "#{postPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getOrderPrice() != null) {
            sql.VALUES("ORDER_PRICE", "#{orderPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getGoodsPayPrice() != null) {
            sql.VALUES("GOODS_PAY_PRICE", "#{goodsPayPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getPostPayPrice() != null) {
            sql.VALUES("POST_PAY_PRICE", "#{postPayPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getOrderPayPrice() != null) {
            sql.VALUES("ORDER_PAY_PRICE", "#{orderPayPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getPayStyle() != null) {
            sql.VALUES("PAY_STYLE", "#{payStyle,jdbcType=CHAR}");
        }
        
        if (record.getBuyEntrance() != null) {
            sql.VALUES("BUY_ENTRANCE", "#{buyEntrance,jdbcType=CHAR}");
        }
        
        if (record.getAreaCodeProvince() != null) {
            sql.VALUES("AREA_CODE_PROVINCE", "#{areaCodeProvince,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaDescProvince() != null) {
            sql.VALUES("AREA_DESC_PROVINCE", "#{areaDescProvince,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaCodeCity() != null) {
            sql.VALUES("AREA_CODE_CITY", "#{areaCodeCity,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaDescCity() != null) {
            sql.VALUES("AREA_DESC_CITY", "#{areaDescCity,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaCodeCounty() != null) {
            sql.VALUES("AREA_CODE_COUNTY", "#{areaCodeCounty,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaDescCounty() != null) {
            sql.VALUES("AREA_DESC_COUNTY", "#{areaDescCounty,jdbcType=VARCHAR}");
        }
        
        if (record.getSchoolName() != null) {
            sql.VALUES("SCHOOL_NAME", "#{schoolName,jdbcType=VARCHAR}");
        }
        
        if (record.getGradeName() != null) {
            sql.VALUES("GRADE_NAME", "#{gradeName,jdbcType=VARCHAR}");
        }
        
        if (record.getClassName() != null) {
            sql.VALUES("CLASS_NAME", "#{className,jdbcType=VARCHAR}");
        }
        
        if (record.getAddressDetail() != null) {
            sql.VALUES("ADDRESS_DETAIL", "#{addressDetail,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("CREATE_TIME", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatePerson() != null) {
            sql.VALUES("UPDATE_PERSON", "#{updatePerson,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("UPDATE_TIME", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReceiverName() != null) {
            sql.VALUES("RECEIVER_NAME", "#{receiverName,jdbcType=VARCHAR}");
        }
        
        if (record.getTelNo() != null) {
            sql.VALUES("TEL_NO", "#{telNo,jdbcType=VARCHAR}");
        }
        
        if (record.getCodeNumber() != null) {
            sql.VALUES("CODE_NUMBER", "#{codeNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getCodeUrl() != null) {
            sql.VALUES("CODE_URL", "#{codeUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getDemo() != null) {
            sql.VALUES("DEMO", "#{demo,jdbcType=VARCHAR}");
        }
        
        if (record.getTradState() != null) {
            sql.VALUES("TRAD_STATE", "#{tradState,jdbcType=CHAR}");
        }
        
        if (record.getShopId() != null) {
            sql.VALUES("SHOP_ID", "#{shopId,jdbcType=BIGINT}");
        }
        
        if (record.getStoreId() != null) {
            sql.VALUES("STORE_ID", "#{storeId,jdbcType=BIGINT}");
        }
        
        if (record.getAgentUserId() != null) {
            sql.VALUES("AGENT_USER_ID", "#{agentUserId,jdbcType=BIGINT}");
        }
        
        if (record.getIsPickup() != null) {
            sql.VALUES("IS_PICKUP", "#{isPickup,jdbcType=CHAR}");
        }
        
        if (record.getExpressCode() != null) {
            sql.VALUES("EXPRESS_CODE", "#{expressCode,jdbcType=VARCHAR}");
        }
        
        if (record.getExpressName() != null) {
            sql.VALUES("EXPRESS_NAME", "#{expressName,jdbcType=VARCHAR}");
        }
        
        if (record.getExpressFee() != null) {
            sql.VALUES("EXPRESS_FEE", "#{expressFee,jdbcType=VARCHAR}");
        }
        
        if (record.getTrackNumber() != null) {
            sql.VALUES("TRACK_NUMBER", "#{trackNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getPayRemark() != null) {
            sql.VALUES("PAY_REMARK", "#{payRemark,jdbcType=VARCHAR}");
        }
        
        if (record.getPayUpdatePerson() != null) {
            sql.VALUES("PAY_UPDATE_PERSON", "#{payUpdatePerson,jdbcType=VARCHAR}");
        }
        
        if (record.getPayUpdateTime() != null) {
            sql.VALUES("PAY_UPDATE_TIME", "#{payUpdateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getRefoundState() != null) {
            sql.VALUES("REFOUND_STATE", "#{refoundState,jdbcType=CHAR}");
        }
        
        if (record.getInvoice() != null) {
            sql.VALUES("INVOICE", "#{invoice,jdbcType=VARCHAR}");
        }
        
        if (record.getPayTime() != null) {
            sql.VALUES("PAY_TIME", "#{payTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSendTime() != null) {
            sql.VALUES("SEND_TIME", "#{sendTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getConfirmTime() != null) {
            sql.VALUES("CONFIRM_TIME", "#{confirmTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIsGroupBuy() != null) {
            sql.VALUES("IS_GROUP_BUY", "#{isGroupBuy,jdbcType=CHAR}");
        }
        
        if (record.getIsRefund() != null) {
            sql.VALUES("IS_REFUND", "#{isRefund,jdbcType=CHAR}");
        }
        
        if (record.getIsAppOrder() != null) {
            sql.VALUES("IS_APP_ORDER", "#{isAppOrder,jdbcType=CHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_order_info
     *
     * @mbg.generated Mon Aug 13 09:47:15 CST 2018
     */
    public String updateByPrimaryKeySelective(OrderInfoGenerateBean record) {
        SQL sql = new SQL();
        sql.UPDATE("order_t_order_info");
        
        if (record.getOrderCode() != null) {
            sql.SET("ORDER_CODE = #{orderCode,jdbcType=CHAR}");
        }
        
        if (record.getBuyerId() != null) {
            sql.SET("BUYER_ID = #{buyerId,jdbcType=BIGINT}");
        }
        
        if (record.getBuyerLogin() != null) {
            sql.SET("BUYER_LOGIN = #{buyerLogin,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderState() != null) {
            sql.SET("ORDER_STATE = #{orderState,jdbcType=CHAR}");
        }
        
        if (record.getGoodsCount() != null) {
            sql.SET("GOODS_COUNT = #{goodsCount,jdbcType=INTEGER}");
        }
        
        if (record.getGoodsPrice() != null) {
            sql.SET("GOODS_PRICE = #{goodsPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getPostPrice() != null) {
            sql.SET("POST_PRICE = #{postPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getOrderPrice() != null) {
            sql.SET("ORDER_PRICE = #{orderPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getGoodsPayPrice() != null) {
            sql.SET("GOODS_PAY_PRICE = #{goodsPayPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getPostPayPrice() != null) {
            sql.SET("POST_PAY_PRICE = #{postPayPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getOrderPayPrice() != null) {
            sql.SET("ORDER_PAY_PRICE = #{orderPayPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getPayStyle() != null) {
            sql.SET("PAY_STYLE = #{payStyle,jdbcType=CHAR}");
        }
        
        if (record.getBuyEntrance() != null) {
            sql.SET("BUY_ENTRANCE = #{buyEntrance,jdbcType=CHAR}");
        }
        
        if (record.getAreaCodeProvince() != null) {
            sql.SET("AREA_CODE_PROVINCE = #{areaCodeProvince,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaDescProvince() != null) {
            sql.SET("AREA_DESC_PROVINCE = #{areaDescProvince,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaCodeCity() != null) {
            sql.SET("AREA_CODE_CITY = #{areaCodeCity,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaDescCity() != null) {
            sql.SET("AREA_DESC_CITY = #{areaDescCity,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaCodeCounty() != null) {
            sql.SET("AREA_CODE_COUNTY = #{areaCodeCounty,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaDescCounty() != null) {
            sql.SET("AREA_DESC_COUNTY = #{areaDescCounty,jdbcType=VARCHAR}");
        }
        
        if (record.getSchoolName() != null) {
            sql.SET("SCHOOL_NAME = #{schoolName,jdbcType=VARCHAR}");
        }
        
        if (record.getGradeName() != null) {
            sql.SET("GRADE_NAME = #{gradeName,jdbcType=VARCHAR}");
        }
        
        if (record.getClassName() != null) {
            sql.SET("CLASS_NAME = #{className,jdbcType=VARCHAR}");
        }
        
        if (record.getAddressDetail() != null) {
            sql.SET("ADDRESS_DETAIL = #{addressDetail,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("CREATE_TIME = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatePerson() != null) {
            sql.SET("UPDATE_PERSON = #{updatePerson,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReceiverName() != null) {
            sql.SET("RECEIVER_NAME = #{receiverName,jdbcType=VARCHAR}");
        }
        
        if (record.getTelNo() != null) {
            sql.SET("TEL_NO = #{telNo,jdbcType=VARCHAR}");
        }
        
        if (record.getCodeNumber() != null) {
            sql.SET("CODE_NUMBER = #{codeNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getCodeUrl() != null) {
            sql.SET("CODE_URL = #{codeUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getDemo() != null) {
            sql.SET("DEMO = #{demo,jdbcType=VARCHAR}");
        }
        
        if (record.getTradState() != null) {
            sql.SET("TRAD_STATE = #{tradState,jdbcType=CHAR}");
        }
        
        if (record.getShopId() != null) {
            sql.SET("SHOP_ID = #{shopId,jdbcType=BIGINT}");
        }
        
        if (record.getStoreId() != null) {
            sql.SET("STORE_ID = #{storeId,jdbcType=BIGINT}");
        }
        
        if (record.getAgentUserId() != null) {
            sql.SET("AGENT_USER_ID = #{agentUserId,jdbcType=BIGINT}");
        }
        
        if (record.getIsPickup() != null) {
            sql.SET("IS_PICKUP = #{isPickup,jdbcType=CHAR}");
        }
        
        if (record.getExpressCode() != null) {
            sql.SET("EXPRESS_CODE = #{expressCode,jdbcType=VARCHAR}");
        }
        
        if (record.getExpressName() != null) {
            sql.SET("EXPRESS_NAME = #{expressName,jdbcType=VARCHAR}");
        }
        
        if (record.getExpressFee() != null) {
            sql.SET("EXPRESS_FEE = #{expressFee,jdbcType=VARCHAR}");
        }
        
        if (record.getTrackNumber() != null) {
            sql.SET("TRACK_NUMBER = #{trackNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getPayRemark() != null) {
            sql.SET("PAY_REMARK = #{payRemark,jdbcType=VARCHAR}");
        }
        
        if (record.getPayUpdatePerson() != null) {
            sql.SET("PAY_UPDATE_PERSON = #{payUpdatePerson,jdbcType=VARCHAR}");
        }
        
        if (record.getPayUpdateTime() != null) {
            sql.SET("PAY_UPDATE_TIME = #{payUpdateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getRefoundState() != null) {
            sql.SET("REFOUND_STATE = #{refoundState,jdbcType=CHAR}");
        }
        
        if (record.getInvoice() != null) {
            sql.SET("INVOICE = #{invoice,jdbcType=VARCHAR}");
        }
        
        if (record.getPayTime() != null) {
            sql.SET("PAY_TIME = #{payTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSendTime() != null) {
            sql.SET("SEND_TIME = #{sendTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getConfirmTime() != null) {
            sql.SET("CONFIRM_TIME = #{confirmTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIsGroupBuy() != null) {
            sql.SET("IS_GROUP_BUY = #{isGroupBuy,jdbcType=CHAR}");
        }
        
        if (record.getIsRefund() != null) {
            sql.SET("IS_REFUND = #{isRefund,jdbcType=CHAR}");
        }
        
        if (record.getIsAppOrder() != null) {
            sql.SET("IS_APP_ORDER = #{isAppOrder,jdbcType=CHAR}");
        }
        
        sql.WHERE("ORDER_ID = #{orderId,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}