package cn.faury.fwmf.module.service.order.generate.sqlProvider;

import cn.faury.fwmf.module.api.order.generate.bean.PostageInfoGenerateBean;
import org.apache.ibatis.jdbc.SQL;

public class PostageInfoGenerateSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_postage_info
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public String insertSelective(PostageInfoGenerateBean record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("order_t_postage_info");
        
        sql.VALUES("POSTAGE_ID", "#{postageId,jdbcType=BIGINT}");
        
        if (record.getPostageName() != null) {
            sql.VALUES("POSTAGE_NAME", "#{postageName,jdbcType=VARCHAR}");
        }
        
        if (record.getPostageType() != null) {
            sql.VALUES("POSTAGE_TYPE", "#{postageType,jdbcType=CHAR}");
        }
        
        if (record.getGoodsCount() != null) {
            sql.VALUES("GOODS_COUNT", "#{goodsCount,jdbcType=INTEGER}");
        }
        
        if (record.getPostagePrice() != null) {
            sql.VALUES("POSTAGE_PRICE", "#{postagePrice,jdbcType=DECIMAL}");
        }
        
        if (record.getIncreaseGoodsCount() != null) {
            sql.VALUES("INCREASE_GOODS_COUNT", "#{increaseGoodsCount,jdbcType=INTEGER}");
        }
        
        if (record.getIncreasePostagePrice() != null) {
            sql.VALUES("INCREASE_POSTAGE_PRICE", "#{increasePostagePrice,jdbcType=DECIMAL}");
        }
        
        if (record.getCreatePerson() != null) {
            sql.VALUES("CREATE_PERSON", "#{createPerson,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("CREATE_TIME", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatePerson() != null) {
            sql.VALUES("UPDATE_PERSON", "#{updatePerson,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("UPDATE_TIME", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_t_postage_info
     *
     * @mbg.generated Sat Aug 04 17:17:43 CST 2018
     */
    public String updateByPrimaryKeySelective(PostageInfoGenerateBean record) {
        SQL sql = new SQL();
        sql.UPDATE("order_t_postage_info");
        
        if (record.getPostageName() != null) {
            sql.SET("POSTAGE_NAME = #{postageName,jdbcType=VARCHAR}");
        }
        
        if (record.getPostageType() != null) {
            sql.SET("POSTAGE_TYPE = #{postageType,jdbcType=CHAR}");
        }
        
        if (record.getGoodsCount() != null) {
            sql.SET("GOODS_COUNT = #{goodsCount,jdbcType=INTEGER}");
        }
        
        if (record.getPostagePrice() != null) {
            sql.SET("POSTAGE_PRICE = #{postagePrice,jdbcType=DECIMAL}");
        }
        
        if (record.getIncreaseGoodsCount() != null) {
            sql.SET("INCREASE_GOODS_COUNT = #{increaseGoodsCount,jdbcType=INTEGER}");
        }
        
        if (record.getIncreasePostagePrice() != null) {
            sql.SET("INCREASE_POSTAGE_PRICE = #{increasePostagePrice,jdbcType=DECIMAL}");
        }
        
        if (record.getCreatePerson() != null) {
            sql.SET("CREATE_PERSON = #{createPerson,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("CREATE_TIME = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatePerson() != null) {
            sql.SET("UPDATE_PERSON = #{updatePerson,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("POSTAGE_ID = #{postageId,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}